---
azs:
- name: z1
  cloud_properties:
    zone: ((zone))
- name: z2
  cloud_properties:
    zone: ((zone))
- name: z3
  cloud_properties:
    zone: ((zone))

networks:
- name: public
  type: dynamic
  subnets:
  - dns:
    - ((internal_ip))
    azs: [z1, z2, z3]
    cloud_properties:
      network_name: ((network))
      subnetwork_name: ((subnetwork))
      ephemeral_external_ip: true

- name: private
  type: dynamic
  subnets:
  - dns:
    - ((internal_ip))
    azs: [z1, z2, z3]
    cloud_properties:
      network_name: ((network))
      subnetwork_name: ((subnetwork))
      ephemeral_external_ip: false
      tags: ((tags))

vm_types:
- name: default
  cloud_properties:
    machine_type: n1-standard-1
    root_disk_size_gb: 20
    root_disk_type: pd-ssd

- name: large
  cloud_properties:
    machine_type: n1-standard-4
    root_disk_size_gb: 20
    root_disk_type: pd-ssd

disk_types:
- name: default
  disk_size: 1024
- name: 1GB
  disk_size: 1024

compilation:
  workers: 5
  network: private
  az: z1
  reuse_compilation_vms: true
  vm_type: default
