name: tinyproxy

releases:
- name: tinyproxy
  version: latest
  url: https://github.com/pivotal-cf-experimental/tinyproxy-release/releases/download/0.0.1/tinyproxy-release-v0.0.1.tgz
  sha1: 30797314c230eaf5ca13982993c159ad0efeef88

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: latest

instance_groups:
- name: tinyproxy
  instances: 1
  networks:
  - name: kubo-network
  azs: [z1]
  jobs:
  - name: tinyproxy
    release: tinyproxy
    properties: {}

  stemcell: trusty
  vm_type: common


update:
  canaries: 1
  max_in_flight: 1
  serial: true
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

variables:
# This can be removed once BOSH supports variables in the runtime-config
- name: /dns_healthcheck_tls_ca
  type: certificate
  options:
    is_ca: true
    common_name: dns-healthcheck-tls-ca

- name: /dns_healthcheck_server_tls
  type: certificate
  options:
    ca: /dns_healthcheck_tls_ca
    common_name: health.bosh-dns
    extended_key_usage:
    - server_auth

- name: /dns_healthcheck_client_tls
  type: certificate
  options:
    ca: /dns_healthcheck_tls_ca
    common_name: health.bosh-dns
    extended_key_usage:
    - client_auth
