---
resources:
- name: govc-release
  type: github-release
  source:
    owner: vmware
    repository: govmomi

- name: git-kubo-ci
  type: git
  source:
    uri: git@github.com:pivotal-cf-experimental/kubo-ci.git
    branch: master
    private_key: ((git-ssh-key))

- name: git-kubo-release
  type: git
  source:
    uri: git@github.com:cloudfoundry-incubator/kubo-release.git
    branch: master
    private_key: ((git-ssh-key))

- name: kubo-ci-stable
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    email: ((docker-hub-email))
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    tag: stable

jobs:
- name: bump-govc
  plan:
  - aggregate:
    - get: git-kubo-ci
    - get: git-kubo-release
    - get: govc-release
      trigger: true
      params: { globs: ["govc_linux_amd64.gz"] }
  - task: bump-govc
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: pcfkubo/kubo-ci
          tag: stable
      run:
        path: git-kubo-ci/scripts/bump-govc.sh
      inputs:
        - name: git-kubo-ci
        - name: git-kubo-release
        - name: govc-release
      outputs:
        - name: git-kubo-release-output
      params:
        ACCESS_KEY_ID: ((gcs-access-key-id))
        SECRET_ACCESS_KEY: ((gcs-secret-access-key))
  - put: git-kubo-release
    params:
      repository: git-kubo-release-output

- name: bump-ci-docker-image
  plan:
  - aggregate:
    - get: git-kubo-ci
    - get: govc-release
      trigger: true
      params: { globs: [""] }
    - get: kubo-ci-stable
      params:
        skip_download: true
  - task: bump-kubo-ci-docker-image
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: pcfkubo/kubo-ci
          tag: stable
      run:
        path: git-kubo-ci/scripts/bump-govc-ci-image.sh
      inputs:
        - name: git-kubo-ci
        - name: govc-release
      outputs:
        - name: git-kubo-ci-output
  - put: kubo-ci-stable
    params:
      build: git-kubo-ci-output/docker-images/kubo-ci
      dockerfile: git-kubo-ci-output/docker-images/kubo-ci/Dockerfile
  - put: git-kubo-ci
    params:
      repository: git-kubo-ci-output
