---
resource_types:
- name: gcs
  type: docker-image
  source:
    repository: frodenas/gcs-resource

resources:
- name: git-kubo-ci
  type: git
  source:
    uri: https://github.com/pivotal-cf-experimental/kubo-ci
    branch: master

- name: git-kubo-release
  type: git
  source:
    uri: git@github.com:cloudfoundry-incubator/kubo-release.git
    branch: master
    private_key: ((git-ssh-key))
    ignore_paths:
    - '*.md'
    - 'LICENSE'
    - 'NOTICE'

- name: git-kubo-etcd
  type: git
  source:
    uri: git@github.com:pivotal-cf-experimental/kubo-etcd.git
    branch: master
    private_key: ((git-ssh-key))
    ignore_paths:
    - '*.md'
    - 'LICENSE'
    - 'NOTICE'

#- name: git-docker-boshrelease
#  type: git
#  source:
#    uri: git@github.com:cloudfoundry-incubator/docker-boshrelease.git
#    branch: master
#    private_key: ((git-ssh-key))
#    ignore_paths:
#    - '*.md'
#    - 'LICENSE'
#    - 'NOTICE'

- name: golang-release
  type: git
  source:
    uri: https://github.com/bosh-packages/golang-release
    branch: master


############################################
# Jobs
############################################
jobs:

- name: bump-kubo-release-golang
  plan:
  - aggregate:
    - get: git-kubo-ci
    - get: git-kubo-release
    - get: golang-release
      trigger: true
  - task: bump-release-golang
    file: git-kubo-ci/tasks/bump-release-golang.yml
    input_mapping: { release: git-kubo-release }
    params:
      ACCESS_KEY_ID: ((gcs-access-key-id))
      SECRET_ACCESS_KEY: ((gcs-secret-access-key))
      MINOR_GO_VERSION: "1.9"
  - put: git-kubo-release
    params:
      repository: modified-release
      rebase: true

- name: bump-kubo-etcd-golang
  plan:
  - aggregate:
    - get: git-kubo-ci
    - get: git-kubo-etcd
    - get: golang-release
      trigger: true
  - task: bump-release-golang
    file: git-kubo-ci/tasks/bump-release-golang.yml
    input_mapping: { release: git-kubo-etcd }
    params:
      ACCESS_KEY_ID: ((gcs-access-key-id))
      SECRET_ACCESS_KEY: ((gcs-secret-access-key))
      MINOR_GO_VERSION: "1.9"
  - put: git-kubo-etcd
    params:
      repository: modified-release
      rebase: true

- name: bump-docker-image-golang
  plan:
    - get: git-kubo-ci
    - get: golang-release
      trigger: true
  - task: bump-golang
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: pcfkubo/kubo-ci
          tag: stable
      run:
        path: git-kubo-ci/scripts/bump-docker-image-golang.sh
      inputs:
        - name: git-kubo-ci
        - name: golang-release
      outputs:
        - name: git-kubo-ci-output
    params:
      ACCESS_KEY_ID: ((gcs-access-key-id))
      SECRET_ACCESS_KEY: ((gcs-secret-access-key))
      MINOR_GO_VERSION: "1.9"
  - put: git-kubo-ci
    params:
      repository: git-kubo-ci-output
      rebase: true


#- name: bump-docker-boshrelease-golang
#  plan:
#  - aggregate:
#    - get: git-kubo-ci
#    - get: git-docker-boshrelease
#    - get: golang-release
#      trigger: true
#  - task: bump-release-golang
#    file: git-kubo-ci/tasks/bump-release-golang.yml
#    input_mapping: { reeease: git-docker-boshrelease }
#    params:
#      ACCESS_KEY_ID: ((gcs-access-key-id))
#      SECRET_ACCESS_KEY: ((gcs-secret-access-key))
#      MINOR_GO_VERSION: "1.9"
#  - put: git-docker-boshrelease
#    params:
#      repository: modified-release
#      rebase: true
