---
resources:
- name: docker-boshrelease
  type: github-release
  source:
    owner: cloudfoundry-incubator
    repository: docker-boshrelease

- name: git-kubo-ci
  type: git
  source:
    uri: git@github.com:pivotal-cf-experimental/kubo-ci.git
    branch: master
    private_key: ((git-ssh-key))

- name: git-kubo-deployment
  type: git
  source:
    uri: git@github.com:cloudfoundry-incubator/kubo-deployment.git
    branch: master
    private_key: ((git-ssh-key))

jobs:
- name: bump-kubo-docker-boshrelease
  plan:
  - aggregate:
    - get: git-kubo-ci
    - get: git-kubo-deployment
    - get: docker-boshrelease
      trigger: true
  - task: bump-kubo-docker
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: pcfkubo/kubo-ci
          tag: stable
      run:
        path: git-kubo-ci/scripts/bump-docker-boshrelease.sh
      inputs:
        - name: git-kubo-ci
        - name: git-kubo-deployment
        - name: docker-boshrelease
      outputs:
        - name: git-kubo-deployment-output
  - put: git-kubo-deployment
    params:
      repository: git-kubo-deployment-output