---
resource_types:
- name: gcs
  type: docker-image
  source:
    repository: frodenas/gcs-resource

- name: github-release-with-version-filtering
  type: docker-image
  source:
    repository: pcfkubo/github-release-resource
    tag: filter-version

resources:
- name: git-kubo-ci
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/kubo-ci
    branch: master

- name: git-kubo-release
  type: git
  source:
    uri: git@github.com:cloudfoundry-incubator/kubo-release.git
    branch: develop
    private_key: ((git-ssh-key.private_key))

- name: git-kubo-deployment
  type: git
  source:
    uri: git@github.com:cloudfoundry-incubator/kubo-deployment.git
    branch: develop
    private_key: ((git-ssh-key.private_key))

- name: git-cfcr-etcd
  type: git
  source:
    uri: git@github.com:cloudfoundry-incubator/cfcr-etcd-release.git
    branch: master
    private_key: ((git-ssh-key.private_key))

- name: git-kubernetes
  type: git
  source:
    uri: https://github.com/kubernetes/kubernetes.git
    branch: master

- name: etcd-release
  type: github-release-with-version-filtering
  source:
    owner: coreos
    repository: etcd
    version_filter: "< 3.4.0"
    access_token: ((github-token-key))

- name: flannel-release
  type: github-release
  source:
    owner: coreos
    repository: flannel
    access_token: ((github-token-key))

- name: boshdns-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/bosh-dns-release

- name: bpm-release
  type: bosh-io-release
  source:
    repository: cloudfoundry-incubator/bpm-release

- name: docker-github-release
  type: github-release
  source:
    owner: cloudfoundry-incubator
    repository: docker-boshrelease
    access_token: ((github-token-key))

- name: k8s-release
  type: github-release-with-version-filtering
  source:
    owner: kubernetes
    repository: kubernetes
    # only patches get updated
    version_filter: "< 1.12.0"
    access_token: ((github-token-key))

- name: heapster-release
  type: github-release
  source:
    owner: kubernetes
    repository: heapster
    access_token: ((github-token-key))

- name: kubernetes-dashboard-release
  type: github-release
  source:
    owner: kubernetes
    repository: dashboard
    access_token: ((github-token-key))

- name: metrics-server-release
  type: github-release
  source:
    owner: kubernetes-incubator
    repository: metrics-server
    access_token: ((github-token-key))

jobs:
- name: bump-boshdns
  plan:
  - aggregate:
    - get: git-kubo-ci
    - get: git-kubo-deployment
    - get: boshdns-release
      trigger: true
  - task: bump-boshdns
    file: git-kubo-ci/tasks/bump-boshrelease.yml
    input_mapping:
      boshrelease: boshdns-release
    params:
      RELEASE_NAME: bosh-dns
  - put: git-kubo-deployment
    params:
      repository: git-kubo-deployment-output

- name: bump-bpm-release
  plan:
  - aggregate:
    - get: git-kubo-ci
    - get: git-kubo-deployment
    - get: bpm-release
      trigger: true
  - task: bump-bpm
    file: git-kubo-ci/tasks/bump-boshrelease.yml
    input_mapping:
      boshrelease: bpm-release
    params:
      RELEASE_NAME: bpm
  - put: git-kubo-deployment
    params:
      repository: git-kubo-deployment-output

- name: bump-docker-boshrelease
  plan:
  - aggregate:
    - get: git-kubo-ci
    - get: git-kubo-deployment
    - get: docker-boshrelease
      resource: docker-github-release
      trigger: true
  - task: bump-docker
    file: git-kubo-ci/tasks/bump-docker-boshrelease.yml
  - put: git-kubo-deployment
    params:
      repository: git-kubo-deployment-output

- name: bump-etcd
  plan:
  - aggregate:
    - get: git-kubo-ci
    - get: git-cfcr-etcd
    - get: etcd-release
      trigger: true
      params: { globs: ["etcd-*-linux-amd64.tar.gz"] }
  - task: bump-etcd-release
    file: git-kubo-ci/tasks/bump-etcd.yml
    params:
      ACCESS_KEY_ID: ((gcs-access-key-id))
      SECRET_ACCESS_KEY: ((gcs-secret-access-key))
  - put: git-cfcr-etcd
    params:
      repository: git-cfcr-etcd-output

- name: bump-flannel
  plan:
  - aggregate:
    - get: git-kubo-ci
    - get: git-kubo-release
    - get: flannel-release
      trigger: true
      params: { globs: ["flannel-v*-linux-amd64.tar.gz"] }
  - task: bump-flannel
    file: git-kubo-ci/tasks/bump-flannel.yml
    params:
      ACCESS_KEY_ID: ((gcs-access-key-id))
      SECRET_ACCESS_KEY: ((gcs-secret-access-key))
  - task: generate-flannel-pr
    file: git-kubo-ci/tasks/create-flannel-pr.yml
    params:
      CFCR_USER_TOKEN: ((cfcr-git-user-token))
      GIT_SSH_KEY: |
        ((git-ssh-key.private_key))

- name: bump-k8s
  plan:
  - aggregate:
    - get: git-kubo-ci
    - get: git-kubo-release
    - get: git-kubernetes
    - get: k8s-release
      trigger: true
  - task: bump-k8s
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: pcfkubo/kubo-ci
          tag: stable
      run:
        path: git-kubo-ci/scripts/bump-k8s.sh
      inputs:
        - name: git-kubo-ci
        - name: git-kubo-release
        - name: k8s-release
        - name: git-kubernetes
      params:
        ACCESS_KEY_ID: ((gcs-access-key-id))
        SECRET_ACCESS_KEY: ((gcs-secret-access-key))
        CFCR_USER_TOKEN: ((cfcr-git-user-token))
        GIT_SSH_KEY: |
          ((git-ssh-key.private_key))

- name: bump-metrics-addons
  plan:
  - aggregate:
    - get: heapster-release
      trigger: true
    - get: kubernetes-dashboard-release
      trigger: true
    - get: metrics-server-release
      trigger: true
    - get: git-kubo-ci
    - get: git-kubo-release
  - task: compare-specs
    file: git-kubo-ci/tasks/bump/compare-specs.yml
  - task: bump-spec
    privileged: true
    file: git-kubo-ci/tasks/bump/bump-k8s-spec.yml
    params:
      ACCESS_KEY_ID: ((gcs-access-key-id))
      SECRET_ACCESS_KEY: ((gcs-secret-access-key))
  - put: git-kubo-release
    params:
      repository: git-kubo-release-output
