groups:
- name: cfcr-etcd-acceptance
  jobs:
  - deploy-turbulence-api-server
  - deploy-long-running-etcd-cluster
  - deploy-network-partition-etcd-cluster
  - deploy-total-network-partition-etcd-cluster
  - deploy-and-run-etcd-acceptance-long-running
  - deploy-and-run-etcd-acceptance-network-partition
  - deploy-and-run-etcd-acceptance-total-network-partition

resource_types:
- name: gcs
  type: docker-image
  source:
    repository: frodenas/gcs-resource

- name: bosh-deployment
  type: docker-image
  source:
    repository: cloudfoundry/bosh-deployment-resource

- name: bosh-errand
  type: docker-image
  source:
    repository: cfcommunity/bosh2-errand-resource

resources:
- name: 60m
  type: time
  source: {interval: 60m}

- name: long-running-etcd-deployment
  type: bosh-deployment
  source:
    deployment: etcd
    target: https://10.100.0.6:25555
    client: admin
    client_secret: ((long-running-etcd-bosh-client-secret))
    ca_cert: ((long-running-etcd-bosh-ca-cert.certificate))

- name: network-partition-etcd-deployment
  type: bosh-deployment
  source:
    deployment: etcd-network-partition
    target: https://10.100.0.6:25555
    client: admin
    client_secret: ((long-running-etcd-bosh-client-secret))
    ca_cert: ((long-running-etcd-bosh-ca-cert.certificate))

- name: total-network-partition-etcd-deployment
  type: bosh-deployment
  source:
    deployment: etcd-total-network-partition
    target: https://10.100.0.6:25555
    client: admin
    client_secret: ((long-running-etcd-bosh-client-secret))
    ca_cert: ((long-running-etcd-bosh-ca-cert.certificate))

- name: long-running-etcd-acceptance-deployment
  type: bosh-deployment
  source:
    deployment: etcd-acceptance
    target: https://10.100.0.6:25555
    client: admin
    client_secret: ((long-running-etcd-bosh-client-secret))
    ca_cert: ((long-running-etcd-bosh-ca-cert.certificate))

- name: network-partition-etcd-acceptance-deployment
  type: bosh-deployment
  source:
    deployment: etcd-acceptance-network-partition
    target: https://10.100.0.6:25555
    client: admin
    client_secret: ((long-running-etcd-bosh-client-secret))
    ca_cert: ((long-running-etcd-bosh-ca-cert.certificate))

- name: total-network-partition-etcd-acceptance-deployment
  type: bosh-deployment
  source:
    deployment: etcd-acceptance-total-network-partition
    target: https://10.100.0.6:25555
    client: admin
    client_secret: ((long-running-etcd-bosh-client-secret))
    ca_cert: ((long-running-etcd-bosh-ca-cert.certificate))

- name: turbulence-deployment
  type: bosh-deployment
  source:
    deployment: turbulence
    target: https://10.100.0.6:25555
    client: admin
    client_secret: ((long-running-etcd-bosh-client-secret))
    ca_cert: ((long-running-etcd-bosh-ca-cert.certificate))

- name: run-etcd-acceptance-errand
  type: bosh-errand
  source:
    deployment: etcd-acceptance
    target: https://10.100.0.6:25555
    client: admin
    client_secret: ((long-running-etcd-bosh-client-secret))
    ca_cert: ((long-running-etcd-bosh-ca-cert.certificate))

- name: run-etcd-acceptance-network-partition-errand
  type: bosh-errand
  source:
    deployment: etcd-acceptance-network-partition
    target: https://10.100.0.6:25555
    client: admin
    client_secret: ((long-running-etcd-bosh-client-secret))
    ca_cert: ((long-running-etcd-bosh-ca-cert.certificate))

- name: run-etcd-acceptance-total-network-partition-errand
  type: bosh-errand
  source:
    deployment: etcd-acceptance-total-network-partition
    target: https://10.100.0.6:25555
    client: admin
    client_secret: ((long-running-etcd-bosh-client-secret))
    ca_cert: ((long-running-etcd-bosh-ca-cert.certificate))

- name: bosh-dns-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/bosh-dns-release

- name: git-kubo-ci
  type: git
  source:
    uri: https://github.com/pivotal-cf-experimental/kubo-ci
    branch: master

- name: git-cfcr-etcd
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/cfcr-etcd-release.git
    branch: master

- name: git-etcd-acceptance
  type: git
  source:
    uri: https://github.com/cfcr/etcd-acceptance-release
    branch: master

- name: gcp-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-google-kvm-ubuntu-xenial-go_agent

jobs:
- name: deploy-turbulence-api-server
  serial: true
  serial_groups: ["deploy_etcd"]
  plan:
  - aggregate:
    - get: gcp-stemcell
      trigger: true
    - get: git-kubo-ci
  - put: turbulence-deployment
    params:
      manifest: git-kubo-ci/manifests/turbulence/etcd-acceptance-turbulence.yml
      vars:
        turbulence_api_ip: 10.100.0.10
        director_ip: 10.100.0.6
        director_client: admin
        director_client_secret: ((long-running-etcd-bosh-client-secret))
        director_ssl.ca: ((long-running-etcd-bosh-ca-cert.certificate))
      stemcells:
      - "gcp-stemcell/*.tgz"
      cleanup: true

- name: deploy-long-running-etcd-cluster
  serial: true
  serial_groups: ["etcd-acceptance", "deploy_etcd"]
  plan:
  - aggregate:
    - get: git-cfcr-etcd
      trigger: true
    - get: git-kubo-ci
    - get: gcp-stemcell
      trigger: true
    - get: bosh-dns-release
      trigger: true
  - task: create-etcd-release
    file: git-kubo-ci/tasks/etcd/create-release.yml
    input_mapping:
      release-dir: git-cfcr-etcd
    output_mapping:
      release: etcd-release
  - put: long-running-etcd-deployment
    params:
      manifest: git-cfcr-etcd/manifests/etcd.yml
      ops_files:
      - "git-kubo-ci/turbulence-agent.yml"
      - "git-cfcr-etcd/manifests/ops-files/share-links.yml"
      stemcells:
      - "gcp-stemcell/*.tgz"
      releases:
      - "etcd-release/*.tgz"
      cleanup: true

- name: deploy-network-partition-etcd-cluster
  serial: true
  serial_groups: ["etcd-acceptance-network-partition", "deploy_etcd"]
  plan:
  - aggregate:
    - get: git-cfcr-etcd
      trigger: true
    - get: git-kubo-ci
    - get: gcp-stemcell
      trigger: true
    - get: bosh-dns-release
      trigger: true
  - task: create-etcd-release
    file: git-kubo-ci/tasks/etcd/create-release.yml
    input_mapping:
      release-dir: git-cfcr-etcd
    output_mapping:
      release: etcd-release
  - put: network-partition-etcd-deployment
    params:
      manifest: git-cfcr-etcd/manifests/etcd.yml
      ops_files:
      - "git-kubo-ci/turbulence-agent.yml"
      - "git-cfcr-etcd/manifests/ops-files/share-links.yml"
      - "git-cfcr-etcd/manifests/ops-files/rename-network-and-deployment.yml"
      vars:
        network-name: default
        deployment-name: etcd-network-partition
      stemcells:
      - "gcp-stemcell/*.tgz"
      releases:
      - "etcd-release/*.tgz"
      cleanup: true

- name: deploy-total-network-partition-etcd-cluster
  serial: true
  serial_groups: ["etcd-acceptance-total-network-partition", "deploy_etcd"]
  plan:
  - aggregate:
    - get: git-cfcr-etcd
      trigger: true
    - get: git-kubo-ci
    - get: gcp-stemcell
      trigger: true
    - get: bosh-dns-release
      trigger: true
  - task: create-etcd-release
    file: git-kubo-ci/tasks/etcd/create-release.yml
    input_mapping:
      release-dir: git-cfcr-etcd
    output_mapping:
      release: etcd-release
  - put: total-network-partition-etcd-deployment
    params:
      manifest: git-cfcr-etcd/manifests/etcd.yml
      ops_files:
      - "git-kubo-ci/turbulence-agent.yml"
      - "git-cfcr-etcd/manifests/ops-files/share-links.yml"
      - "git-cfcr-etcd/manifests/ops-files/rename-network-and-deployment.yml"
      vars:
        network-name: default
        deployment-name: etcd-total-network-partition
      stemcells:
      - "gcp-stemcell/*.tgz"
      releases:
      - "etcd-release/*.tgz"
      cleanup: true

- name: deploy-and-run-etcd-acceptance-long-running
  serial: true
  serial_groups: ["etcd-acceptance"]
  plan:
  - aggregate:
    - get: 60m
      trigger: true
    - get: git-cfcr-etcd
      trigger: true
      passed: [deploy-long-running-etcd-cluster]
    - get: git-etcd-acceptance
      trigger: true
    - get: git-kubo-ci
    - get: gcp-stemcell
      trigger: true
      passed: [deploy-long-running-etcd-cluster]
    - get: bosh-dns-release
      trigger: true
      passed: [deploy-long-running-etcd-cluster]
  - task: create-etcd-acceptance-release
    file: git-kubo-ci/tasks/etcd/create-release.yml
    input_mapping:
      release-dir: git-etcd-acceptance
    output_mapping:
      release: etcd-acceptance-release
  - put: long-running-etcd-acceptance-deployment
    params:
      manifest: git-etcd-acceptance/deployment/etcd-acceptance.yml
      stemcells:
      - "gcp-stemcell/*.tgz"
      releases:
      - "etcd-acceptance-release/*.tgz"
      cleanup: true
      vars:
        director-url: https://10.100.0.6:25555
        uaa-url: https://10.100.0.6:8443
        director-ca: ((long-running-etcd-bosh-ca-cert.certificate))
        director-client-secret: ((long-running-etcd-bosh-client-secret))
        etcd-deployment-name: etcd
  - put: run-etcd-acceptance-errand
    params:
      name: read-availability-during-recreate
      keep_alive: true

- name: deploy-and-run-etcd-acceptance-network-partition
  serial: true
  serial_groups: ["etcd-acceptance-network-partition"]
  plan:
  - aggregate:
    - get: 60m
      trigger: true
    - get: git-cfcr-etcd
      trigger: true
      passed: [deploy-network-partition-etcd-cluster]
    - get: git-etcd-acceptance
      trigger: true
    - get: git-kubo-ci
    - get: gcp-stemcell
      trigger: true
      passed: [deploy-network-partition-etcd-cluster]
    - get: bosh-dns-release
      trigger: true
      passed: [deploy-network-partition-etcd-cluster]
  - task: create-etcd-acceptance-release
    file: git-kubo-ci/tasks/etcd/create-release.yml
    input_mapping:
      release-dir: git-etcd-acceptance
    output_mapping:
      release: etcd-acceptance-release
  - put: network-partition-etcd-acceptance-deployment
    params:
      manifest: git-etcd-acceptance/deployment/etcd-acceptance.yml
      ops_files:
      - "git-kubo-ci/etcd/deployment-name.yml"
      stemcells:
      - "gcp-stemcell/*.tgz"
      releases:
      - "etcd-acceptance-release/*.tgz"
      cleanup: true
      vars:
        director-url: https://10.100.0.6:25555
        uaa-url: https://10.100.0.6:8443
        director-ca: ((long-running-etcd-bosh-ca-cert.certificate))
        director-client-secret: ((long-running-etcd-bosh-client-secret))
        etcd-deployment-name: etcd-network-partition
        deployment-name: etcd-acceptance-network-partition
  - put: run-etcd-acceptance-network-partition-errand
    params:
      name: read-availability-during-network-partition
      keep_alive: true
    ensure:
      task: restart-etcd-cluster
      file: git-kubo-ci/tasks/etcd/restart-cluster.yml
      params:
        BOSH_CA_CERT: ((long-running-etcd-bosh-ca-cert.certificate))
        BOSH_CLIENT: admin
        BOSH_CLIENT_SECRET: ((long-running-etcd-bosh-client-secret))
        BOSH_DEPLOYMENT: etcd-network-partition
        BOSH_ENVIRONMENT: https://10.100.0.6:25555

- name: deploy-and-run-etcd-acceptance-total-network-partition
  serial: true
  serial_groups: ["etcd-acceptance-total-network-partition"]
  plan:
  - aggregate:
    - get: 60m
      trigger: true
    - get: git-cfcr-etcd
      trigger: true
      passed: [deploy-total-network-partition-etcd-cluster]
    - get: git-etcd-acceptance
      trigger: true
    - get: git-kubo-ci
    - get: gcp-stemcell
      trigger: true
      passed: [deploy-total-network-partition-etcd-cluster]
    - get: bosh-dns-release
      trigger: true
      passed: [deploy-total-network-partition-etcd-cluster]
  - task: create-etcd-acceptance-release
    file: git-kubo-ci/tasks/etcd/create-release.yml
    input_mapping:
      release-dir: git-etcd-acceptance
    output_mapping:
      release: etcd-acceptance-release
  - put: total-network-partition-etcd-acceptance-deployment
    params:
      manifest: git-etcd-acceptance/deployment/etcd-acceptance.yml
      ops_files:
      - "git-kubo-ci/etcd/deployment-name.yml"
      stemcells:
      - "gcp-stemcell/*.tgz"
      releases:
      - "etcd-acceptance-release/*.tgz"
      cleanup: true
      vars:
        director-url: https://10.100.0.6:25555
        uaa-url: https://10.100.0.6:8443
        director-ca: ((long-running-etcd-bosh-ca-cert.certificate))
        director-client-secret: ((long-running-etcd-bosh-client-secret))
        etcd-deployment-name: etcd-total-network-partition
        deployment-name: etcd-acceptance-total-network-partition
  - put: run-etcd-acceptance-total-network-partition-errand
    params:
      name: read-availability-during-total-network-partition
      keep_alive: true
