---
resources:
- name: git-kubo-ci
  type: git
  source:
    uri: git@github.com:pivotal-cf-experimental/kubo-ci.git
    branch: master
    private_key: ((git-ssh-key.private_key))

jobs:
- name: clean-gcp-disks
  plan:
  - task: cleanup-disks
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: { repository: google/cloud-sdk }
      params:
        GCP_SERVICE_ACCOUNT: ((gcp-service-account))
      run:
        path: /bin/bash
        args:
        - -eux
        - -c
        - |
          export GOOGLE_APPLICATION_CREDENTIALS="$(mktemp)"
          set +x
          echo "$GCP_SERVICE_ACCOUNT" > "$GOOGLE_APPLICATION_CREDENTIALS"
          set -x
          gcloud auth activate-service-account --key-file $GOOGLE_APPLICATION_CREDENTIALS --project cf-pcf-kubo
          disks_to_delete="$(gcloud compute disks list --format='value(selfLink)' --filter='-users:*')"
          if [[ "$disks_to_delete" != "" ]]; then
            gcloud -q compute disks delete $disks_to_delete
          fi

- name: clean-gcp-lbs
  plan:
  - get: git-kubo-ci
  - task: cleanup-lbs
    file: git-kubo-ci/tasks/cleanup-gcp-lbs.yml
    config:
      inputs:
        - name: git-kubo-ci
      params:
        GCP_SERVICE_ACCOUNT: ((gcp-service-account))
