---
resources:
- name: git-kubo-ci
  type: git
  source:
    uri: git@github.com:pivotal-cf-experimental/kubo-ci.git
    branch: master
    private_key: ((git-ssh-key.private_key))

jobs:
- name: clean-gcp-disks
  plan:
  - get: git-kubo-ci
  - task: cleanup-disks
    file: git-kubo-ci/tasks/cleanup-gcp-disks.yml
    params:
      GCP_SERVICE_ACCOUNT: ((gcp-service-account))

- name: clean-gcp-lbs
  plan:
  - get: git-kubo-ci
  - task: cleanup-lbs
    file: git-kubo-ci/tasks/cleanup-gcp-lbs.yml
    params:
      GCP_SERVICE_ACCOUNT: ((gcp-service-account))
