groups:
- name: kubo-etcd
  jobs:
  - run-unit-tests
  - setup-eats-infrastructure
  - eats
  - eats-turbulence
  - teardown-eats-infrastructure
- name: etcd-acceptance
  jobs:
  - deploy-long-running-etcd
  - deploy-and-run-etcd-acceptance

resource_types:
- name: gcs
  type: docker-image
  source:
    repository: frodenas/gcs-resource

- name: bosh-deployment
  type: docker-image
  source:
    repository: cloudfoundry/bosh-deployment-resource

resources:
- name: 30m
  type: time
  source: {interval: 30m}

- name: long-running-etcd-deployment
  type: bosh-deployment
  source:
    deployment: etcd
    target: https://10.100.0.6:25555
    client: admin
    client_secret: ((long-running-etcd-bosh-client-secret))
    ca_cert: ((long-running-etcd-bosh-ca-cert.certificate))

- name: long-running-etcd-acceptance-deployment
  type: bosh-deployment
  source:
    deployment: etcd-acceptance
    target: https://10.100.0.6:25555
    client: admin
    client_secret: ((long-running-etcd-bosh-client-secret))
    ca_cert: ((long-running-etcd-bosh-ca-cert.certificate))

- name: bosh-dns-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/bosh-dns-release

- name: git-kubo-ci
  type: git
  source:
    uri: https://github.com/pivotal-cf-experimental/kubo-ci
    branch: master

- name: git-kubo-etcd
  type: git
  source:
    uri: https://github.com/pivotal-cf-experimental/kubo-etcd
    branch: master

- name: git-etcd-acceptance
  type: git
  source:
    uri: https://github.com/jfmyers9/etcd-acceptance-release
    branch: master

- name: git-kubo-etcd-clustered
  type: git
  source:
    uri: https://github.com/pivotal-cf-experimental/kubo-etcd
    branch: wip-154321671-etcd-experiment

- name: kubo-lock
  type: pool
  source:
    uri: git@github.com:pivotal-cf-experimental/kubo-locks.git
    branch: master
    private_key: ((git-ssh-key))
    pool: kubo-gcp

- name: gcs-kubo-deployment-pre
  type: gcs
  source:
    json_key: ((gcs-json-key))
    bucket: kubo-public
    versioned_file: kubo-deployment-latest.tgz

- name: gcs-bosh-creds
  type: gcs
  source:
    json_key: ((gcs-json-key))
    bucket: kubo-pipeline-store
    versioned_file: bosh/creds.yml

- name: gcs-bosh-state
  type: gcs
  source:
    json_key: ((gcs-json-key))
    bucket: kubo-pipeline-store
    versioned_file: bosh/state.json

- name: gcp-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-google-kvm-ubuntu-trusty-go_agent

- name: turbulence-release
  type: bosh-io-release
  source:
    repository: cppforlife/turbulence-release

- name: consul-release
  type: bosh-io-release
  source:
    repository: cloudfoundry-incubator/consul-release

- name: latest-etcd-release
  type: gcs
  source:
    json_key: ((gcs-json-key))
    bucket: kubo-public
    versioned_file: latest-kubo-etcd.tgz

jobs:
- name: run-unit-tests
  public: true
  plan:
  - aggregate:
    - get: git-kubo-etcd
      trigger: true
    - get: git-kubo-ci
  - aggregate:
    - task: test-etcd-proxy
      file: git-kubo-ci/scripts/etcd/run-unit-test-suite/task.yml
      input_mapping:
        ci: git-kubo-ci
        etcd-release: git-kubo-etcd
      params:
        TEST_SUITE: etcd-proxy
    - task: test-etcd-consistency-checker
      file: git-kubo-ci/scripts/etcd/run-unit-test-suite/task.yml
      input_mapping:
        ci: git-kubo-ci
        etcd-release: git-kubo-etcd
      params:
        TEST_SUITE: etcd-consistency-checker
    - task: test-etcdfab
      file: git-kubo-ci/scripts/etcd/run-unit-test-suite/task.yml
      input_mapping:
        ci: git-kubo-ci
        etcd-release: git-kubo-etcd
      params:
        TEST_SUITE: etcdfab
    - task: test-etcd-metrics-server
      file: git-kubo-ci/scripts/etcd/test-etcd-metrics-server/task.yml
      input_mapping:
        ci: git-kubo-ci
        etcd-release: git-kubo-etcd

- name: setup-eats-infrastructure
  public: true
  plan:
  - aggregate:
    - get: git-kubo-etcd
      trigger: true
      passed: [ run-unit-tests ]
    - get: git-kubo-ci
    - get: gcs-kubo-deployment-pre
  - put: kubo-lock
    params: { acquire: true }
  - task: unpack-kubo-deployment
    file: git-kubo-ci/tasks/unpack-kubo-deployment.yml
  - task: install
    file: git-kubo-ci/tasks/etcd/setup-eats-infrastructure.yml
  - aggregate:
    - put: gcs-bosh-creds
      params:
        file: bosh-creds/creds.yml
    - put: gcs-bosh-state
      params:
        file: bosh-state/state.json

- name: eats
  public: true
  plan:
  - aggregate:
    - get: gcs-bosh-state
      passed:
      - setup-eats-infrastructure
    - get: gcs-bosh-creds
      passed:
      - setup-eats-infrastructure
    - get: kubo-lock
      trigger: true
      passed:
      - setup-eats-infrastructure
    - get: etcd-release
      resource: git-kubo-etcd
      passed:
      - setup-eats-infrastructure
    - get: stemcell
      resource: gcp-stemcell
    - get: turbulence-release
    - get: consul-release
    - get: latest-etcd-release
    - get: git-kubo-ci
  - task: run-eats
    file: git-kubo-ci/tasks/etcd/run-eats.yml
    input_mapping:
      ci: git-kubo-ci
    params:
      TEST_enable_turbulence_tests: false
      TEST_parallel_nodes: 5

- name: eats-turbulence
  public: true
  plan:
  - aggregate:
    - get: gcs-bosh-state
      passed:
      - eats
    - get: gcs-bosh-creds
      passed:
      - eats
    - get: kubo-lock
      trigger: true
      passed:
      - eats
    - get: etcd-release
      resource: git-kubo-etcd
      passed:
      - eats
    - get: stemcell
      resource: gcp-stemcell
    - get: turbulence-release
    - get: consul-release
    - get: latest-etcd-release
    - get: git-kubo-ci
  - task: run-eats
    file: git-kubo-ci/tasks/etcd/run-eats.yml
    input_mapping:
      ci: git-kubo-ci
    params:
      TEST_enable_turbulence_tests: true
      TEST_parallel_nodes: 3

- name: teardown-eats-infrastructure
  plan:
  - aggregate:
    - get: git-kubo-ci
    - get: kubo-lock
      version: every
      trigger: true
      passed: [ 'eats-turbulence' ]
    - get: gcs-kubo-deployment-pre
    - get: gcs-bosh-state
      passed: [ 'eats-turbulence' ]
    - get: gcs-bosh-creds
      passed: [ 'eats-turbulence' ]
  - task: unpack-kubo-deployment
    file: git-kubo-ci/tasks/unpack-kubo-deployment.yml
  - task: destroy
    file: git-kubo-ci/tasks/destroy-bosh.yml
  - put: kubo-lock
    params: { release: kubo-lock }

- name: deploy-long-running-etcd
  serial: true
  serial_groups: ["etcd-acceptance"]
  plan:
  - aggregate:
    - get: git-kubo-etcd-clustered
      trigger: true
    - get: git-kubo-ci
    - get: gcp-stemcell
      trigger: true
    - get: bosh-dns-release
      trigger: true
  - task: create-etcd-release
    file: git-kubo-ci/tasks/etcd/create-release.yml
    input_mapping:
      release-dir: git-kubo-etcd-clustered
    output_mapping:
      release: etcd-release
  - put: long-running-etcd-deployment
    params:
      manifest: git-kubo-etcd-clustered/manifests/3-node-with-ssl-bosh-dns.yml
      stemcells:
      - "gcp-stemcell/*.tgz"
      releases:
      - "etcd-release/*.tgz"
      - "bosh-dns-release/*.tgz"
      cleanup: true

- name: deploy-and-run-etcd-acceptance
  serial: true
  serial_groups: ["etcd-acceptance"]
  plan:
  - aggregate:
    - get: 30m
      trigger: true
    - get: git-kubo-etcd-clustered
      trigger: true
      passed: [deploy-long-running-etcd]
    - get: git-etcd-acceptance
      trigger: true
    - get: git-kubo-ci
    - get: gcp-stemcell
      trigger: true
      passed: [deploy-long-running-etcd]
    - get: bosh-dns-release
      trigger: true
      passed: [deploy-long-running-etcd]
  - task: create-etcd-acceptance-release
    file: git-kubo-ci/tasks/etcd/create-release.yml
    input_mapping:
      release-dir: git-etcd-acceptance
    output_mapping:
      release: etcd-acceptance-release
  - put: long-running-etcd-acceptance-deployment
    params:
      manifest: git-etcd-acceptance/deployment/etcd-acceptance.yml
      stemcells:
      - "gcp-stemcell/*.tgz"
      releases:
      - "etcd-acceptance-release/*.tgz"
      - "bosh-dns-release/*.tgz"
      cleanup: true
      vars:
        director-url: https://10.100.0.6:25555
        uaa-url: https://10.100.0.6:8443
        director-ca: ((long-running-etcd-bosh-ca-cert.certificate))
        director-client-secret: ((long-running-etcd-bosh-client-secret))
        tls-etcd-client: ((/long-running-etcd-director/etcd/tls-etcd-client)) # cert generated in separate deployment
  - task: run-read-availability-during-recreate-errand
    file: git-kubo-ci/tasks/etcd/run-errand.yml
    params:
      BOSH_CA_CERT: ((long-running-etcd-bosh-ca-cert.certificate))
      BOSH_CLIENT: admin
      BOSH_CLIENT_SECRET: ((long-running-etcd-bosh-client-secret))
      BOSH_DEPLOYMENT: etcd-acceptance
      BOSH_ENVIRONMENT: https://10.100.0.6:25555
      ERRAND_NAME: read-availability-during-recreate
