resources:
- name: git-kubo-ci
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/kubo-ci
    branch: master
    paths: [src/jobspec]

jobs:
- name: run-unit-tests
  plan:
  - get: git-kubo-ci
    trigger: true
  - task: run-release-unit-tests
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: pcfkubo/kubo-ci
          tag: stable
      inputs:
      - name: git-kubo-ci
      run:
        path: /bin/bash
        args:
        - -exc
        - |
          cd git-kubo-ci/src/jobspec/flag_generator
          GO111MODULE=on go mod vendor
          ginkgo -v -r .
