---
resources:
- name: git-kubo-ci
  type: git
  source:
    uri: https://github.com/pivotal-cf-experimental/kubo-ci
    branch: master

- name: git-kubo-release
  type: git
  source:
    uri: git@github.com:BenChapman/kubo-release #TODO: https://github.com/cloudfoundry-incubator/kubo-release
    branch: master
    ignore_paths:
    - '*.md'
    - 'LICENSE'
    - 'NOTICE'
    private_key: ((git-ssh-key))

- name: git-kubo-deployment
  type: git
  source:
    uri: git@github.com:BenChapman/kubo-deployment #TODO: https://github.com/cloudfoundry-incubator/kubo-release
    branch: master
    private_key: ((git-ssh-key))

- name: gcs-kubo-release-tarball
  type: gcs
  source:
    json_key: ((gcs-json-key))
    bucket: kubo-public
    versioned_file: kubo-release-latest.tgz

- name: kubo-version
  type: semver
  source:
    key: kubo-version-test
    access_key_id: ((gcs-access-key-id))
    secret_access_key: ((gcs-secret-access-key))
    bucket: kubo-pipeline-store
    region_name: europe-west1
    endpoint: storage.googleapis.com

- name: gh-release-kubo-release
  type: github-release
  source:
    owner: BenChapman
    repository: kubo-release
    access_token: ((github-token-key))
    drafts: true

- name: gh-release-kubo-deployment
  type: github-release
  source:
    owner: BenChapman
    repository: kubo-deployment
    access_token: ((github-token-key))
    drafts: true

jobs:
- name: finalize-kubo-release
  plan:
  - aggregate:
    - get: git-kubo-ci
    - get: kubo-version
      params:
        bump: final
    - get: git-kubo-release
    - get: git-kubo-deployment
    - get: gcs-kubo-release-tarball
  - task: finalize-release
    file: git-kubo-ci/tasks/finalize-kubo-release.yml
    params:
      ACCESS_KEY_ID: ((gcs-access-key-id))
      SECRET_ACCESS_KEY: ((gcs-secret-access-key))
  - aggregate:
    - put: git-kubo-release
      params:
        repository: git-kubo-release-output
    - put: git-kubo-deployment
      params:
        repository: git-kubo-deployment
        tag: kubo-release/tag
    - put: gh-release-kubo-release
      params:
        name: kubo-release/name
        tag: kubo-release/tag
        body: kubo-release/body
        globs: ["kubo-release/*.tgz"]
    - put: gh-release-kubo-release
      params:
        name: kubo-deployment/name
        tag: kubo-deployment/tag
        body: kubo-deployment/body
  - put: kubo-version
    params:
      bump: patch

