---
resource_types:
- name: gcs
  type: docker-image
  source:
    repository: frodenas/gcs-resource

resources:
- name: git-kubo-ci
  type: git
  source:
    uri: https://github.com/pivotal-cf-experimental/kubo-ci
    branch: master

- name: git-kubo-release
  type: git
  source:
    uri: https://github.com/BenChapman/kubo-release #TODO: https://github.com/cloudfoundry-incubator/kubo-release
    branch: master
    ignore_paths:
    - '*.md'
    - 'LICENSE'
    - 'NOTICE'
    private_key: ((git-ssh-key)) #has both public & private keys in credhub, how do we get just the private key?

- name: gcs-kubo-release-tarball
  type: gcs
  source:
    json_key: ((gcs-json-key))
    bucket: kubo-public
    versioned_file: kubo-release-latest.tgz

- name: kubo-version
  type: semver
  source:
    key: kubo-version
    access_key_id: ((gcs-access-key-id))
    secret_access_key: ((gcs-secret-access-key))
    bucket: kubo-release-blobs-test # TODO: kubo-pipeline-store
    region_name: europe-west1
    endpoint: storage.googleapis.com

jobs:
- name: finalize-kubo-release
  plan:
  - aggregate:
    - get: git-kubo-ci
    - get: kubo-version
      params:
        bump: final
    - get: git-kubo-release
    - get: gcs-kubo-release-tarball
  - task: finalize-release
    file: git-kubo-ci/tasks/finalize-kubo-release.yml
    params:
      ACCESS_KEY_ID: ((gcs-access-key-id))
      SECRET_ACCESS_KEY: ((gcs-secret-access-key))
  - put: git-kubo-release
    params:
      repository: git-kubo-release-output
  - put: kubo-version
    params:
      bump: patch

