<%
  stemcell_types = {'gcp-lb' => 'google-kvm', 'vsphere' => 'vsphere-esxi'}
  iaas_list = %w(gcp-lb vsphere)
%>
---
groups:
- name: all
  jobs:
<% iaas_list.each do |iaas| %>
  - claim-lock-<%= iaas %>
  - install-old-bosh-<%= iaas %>
  - deploy-old-k8s-<%= iaas %>
  - deploy-workload-<%= iaas %>
  - upgrade-stemcell-<%= iaas %>
  - upgrade-bosh-and-kubo-<%= iaas %>
  - destroy-k8s-<%= iaas %>
  - destroy-bosh-<%= iaas %>
<% end %>
<% iaas_list.each do |iaas| %>
- name: <%= iaas %>
  jobs:
  - claim-lock-<%= iaas %>
  - install-old-bosh-<%= iaas %>
  - deploy-old-k8s-<%= iaas %>
  - deploy-workload-<%= iaas %>
  - upgrade-stemcell-<%= iaas %>
  - upgrade-bosh-and-kubo-<%= iaas %>
  - destroy-k8s-<%= iaas %>
  - destroy-bosh-<%= iaas %>
<% end %>
resource_types:
- name: gcs
  type: docker-image
  source:
    repository: frodenas/gcs-resource

resources:
- name: git-kubo-ci
  type: git
  source:
    uri: https://github.com/pivotal-cf-experimental/kubo-ci
    branch: master

<% iaas_list.each do |iaas| %>
- name: kubo-lock-<%= iaas %>
  type: pool
  source:
    uri: git@github.com:pivotal-cf-experimental/kubo-locks.git
    branch: master
    private_key: ((git-ssh-key))
    pool: kubo-<%= iaas %>
<% end %>

- name: gcs-bosh-state
  type: gcs
  source:
    json_key: ((gcs-json-key))
    bucket: kubo-pipeline-store
    versioned_file: bosh/state.json

- name: gcs-bosh-creds
  type: gcs
  source:
    json_key: ((gcs-json-key))
    bucket: kubo-pipeline-store
    versioned_file: bosh/creds.yml

- name: new-kubo-release-tarball
  type: gcs
  source:
    json_key: ((gcs-json-key))
    bucket: kubo-public
    versioned_file: kubo-release-latest.tgz

- name: new-kubo-deployment-tarball
  type: gcs
  source:
    json_key: ((gcs-json-key))
    bucket: kubo-public
    versioned_file: kubo-deployment-latest.tgz

# old version of kubo
- name: old-kubo-release-tarball
  type: github-release
  source:
    owner: cloudfoundry-incubator
    repository: kubo-release
    pre_release: true
    access_token: ((github-kubo-gitbot-access-token))

- name: old-kubo-deployment-tarball
  type: github-release
  source:
    owner: cloudfoundry-incubator
    repository: kubo-deployment
    pre_release: true
    access_token: ((github-kubo-gitbot-access-token))

<% iaas_list.each do |iaas| %>
- name: new-bosh-stemcell-<%= iaas %>
  type: bosh-io-stemcell
  source:
    name: bosh-<%= stemcell_types[iaas] %>-ubuntu-trusty-go_agent
    version: 3445.11
<% end %>

- name: nightly
  type: time
  source:
    start: 5:00 AM
    stop: 6:00 AM
    location: Europe/Dublin


##########################################
# Jobs
##########################################

jobs:

<% iaas_list.each do |iaas| %>
- name: claim-lock-<%= iaas %>
  max_in_flight: 1
  plan:
  - get: nightly
    trigger: true
  - put: kubo-lock-<%= iaas %>
    params: { acquire: true }

- name: install-old-bosh-<%= iaas %>
  plan:
  - aggregate:
    - get: git-kubo-ci
    - get: old-kubo-deployment-tarball
    - get: kubo-lock-<%= iaas %>
      version: every
      trigger: true
      passed: [ 'claim-lock-<%= iaas %>' ]

  - task: unpack-tgz
    file: git-kubo-ci/tasks/unpack-tgz.yml
    tags: ['<%= iaas %>']
    input_mapping:
      source_tarball: old-kubo-deployment-tarball
    params:
      SOURCE_TARBALL_REGEX: kubo-deployment-*.tgz
      COLLAPSE_DIR: kubo-deployment-*/kubo-deployment

  - task: install
    tags: [<%= iaas %>]
    file: git-kubo-ci/tasks/install-bosh.yml
    input_mapping:
      kubo-lock: kubo-lock-<%= iaas %>
      git-kubo-deployment: unpacked_dir

  - aggregate:
    - put: gcs-bosh-creds
      params:
        file: bosh-creds/creds.yml
    - put: gcs-bosh-state
      params:
        file: bosh-state/state.json

- name: deploy-old-k8s-<%= iaas %>
  plan:
  - aggregate:
    - get: git-kubo-ci
    - get: kubo-lock-<%= iaas %>
      version: every
      trigger: true
      passed: [ 'install-old-bosh-<%= iaas %>' ]
    - get: old-kubo-deployment-tarball
      passed: [ 'install-old-bosh-<%= iaas %>' ]
    - get: gcs-bosh-state
      passed: [ 'install-old-bosh-<%= iaas %>' ]
    - get: gcs-bosh-creds
      passed: [ 'install-old-bosh-<%= iaas %>' ]
    - get: old-kubo-release-tarball

  - task: unpack-tgz
    file: git-kubo-ci/tasks/unpack-tgz.yml
    tags: ['<%= iaas %>']
    input_mapping:
      source_tarball: old-kubo-deployment-tarball
    params:
      SOURCE_TARBALL_REGEX: kubo-deployment-*.tgz
      COLLAPSE_DIR: kubo-deployment-*/kubo-deployment

  - task: deploy
    tags: [<%= iaas %>]
    input_mapping:
      gcs-kubo-release-tarball: old-kubo-release-tarball
      kubo-lock: kubo-lock-<%= iaas %>
      git-kubo-deployment: unpacked_dir
    file: git-kubo-ci/tasks/deploy-k8s-instance.yml

- name: deploy-workload-<%= iaas %>
  plan:
  - aggregate:
    - get: git-kubo-ci
    - get: kubo-lock-<%= iaas %>
      version: every
      trigger: true
      passed: [ 'deploy-old-k8s-<%= iaas %>' ]
    - get: new-kubo-deployment-tarball
    - get: gcs-bosh-state
      passed: [ 'deploy-old-k8s-<%= iaas %>' ]
    - get: gcs-bosh-creds
      passed: [ 'deploy-old-k8s-<%= iaas %>' ]

  - task: unpack-tgz
    file: git-kubo-ci/tasks/unpack-tgz.yml
    tags: ['<%= iaas %>']
    input_mapping:
      source_tarball: new-kubo-deployment-tarball
    params:
      SOURCE_TARBALL_REGEX: kubo-deployment-*.tgz
      COLLAPSE_DIR: kubo-deployment

  - task: deploy
    tags: ['<%= iaas %>']
    file: git-kubo-ci/tasks/deploy-k8s-workload.yml
    input_mapping:
      git-kubo-deployment: unpacked_dir
      kubo-lock: kubo-lock-<%= iaas %>

- name: upgrade-stemcell-<%= iaas %>
  plan:
  - aggregate:
    - get: git-kubo-ci
    - get: kubo-lock-<%= iaas %>
      version: every
      trigger: true
      passed: [ 'deploy-workload-<%= iaas %>' ]
    - get: old-kubo-deployment-tarball
      passed: [ 'deploy-old-k8s-<%= iaas %>' ]
    - get: old-kubo-release-tarball
      passed: [ 'deploy-old-k8s-<%= iaas %>' ]
    - get: gcs-bosh-state
      passed: [ 'deploy-workload-<%= iaas %>' ]
    - get: gcs-bosh-creds
      passed: [ 'deploy-workload-<%= iaas %>' ]
    - get: new-bosh-stemcell-<%= iaas %>
      params:
        tarball: false

  - task: unpack-tgz
    file: git-kubo-ci/tasks/unpack-tgz.yml
    tags: ['<%= iaas %>']
    input_mapping:
      source_tarball: old-kubo-deployment-tarball
    params:
      SOURCE_TARBALL_REGEX: kubo-deployment-*.tgz
      COLLAPSE_DIR: kubo-deployment-*/kubo-deployment

  - task: upgrade
    tags: ['<%= iaas %>']
    file: git-kubo-ci/tasks/upgrade-stemcell.yml
    input_mapping:
      kubo-lock: kubo-lock-<%= iaas %>
      git-kubo-deployment: unpacked_dir
      gcs-kubo-release-tarball: old-kubo-release-tarball
      new-bosh-stemcell: new-bosh-stemcell-<%= iaas %>
    params:
      HA_MIN_SERVICE_AVAILABILITY: "0.99"

- name: upgrade-bosh-and-kubo-<%= iaas %>
  plan:
  - aggregate:
    - get: git-kubo-ci
    - get: kubo-lock-<%= iaas %>
      version: every
      trigger: true
      passed: [ 'upgrade-stemcell-<%= iaas %>' ]
    - get: new-kubo-deployment-tarball
    - get: new-kubo-release-tarball
    - get: gcs-bosh-state
      passed: [ 'upgrade-stemcell-<%= iaas %>' ]
    - get: gcs-bosh-creds
      passed: [ 'upgrade-stemcell-<%= iaas %>' ]

  - task: unpack-tgz
    file: git-kubo-ci/tasks/unpack-tgz.yml
    tags: ['<%= iaas %>']
    input_mapping:
      source_tarball: new-kubo-deployment-tarball
    params:
      SOURCE_TARBALL_REGEX: kubo-deployment-*.tgz
      COLLAPSE_DIR: kubo-deployment

  - task: upgrade
    tags: ['<%= iaas %>']
    file: git-kubo-ci/tasks/upgrade-bosh-and-kubo.yml
    input_mapping:
      kubo-lock: kubo-lock-<%= iaas %>
      git-kubo-deployment: unpacked_dir
      gcs-kubo-release-tarball: new-kubo-release-tarball
    params:
      HA_MIN_SERVICE_AVAILABILITY: "0.99"

  - aggregate:
    - put: gcs-bosh-creds
      params:
        file: bosh-creds/creds.yml
    - put: gcs-bosh-state
      params:
        file: bosh-state/state.json

- name: destroy-k8s-<%= iaas %>
  plan:
  - aggregate:
    - get: git-kubo-ci
    - get: kubo-lock-<%= iaas %>
      version: every
      trigger: true
      passed: [ 'upgrade-bosh-and-kubo-<%= iaas %>' ]
    - get: new-kubo-deployment-tarball
      passed: [ 'upgrade-bosh-and-kubo-<%= iaas %>' ]
    - get: gcs-bosh-state
      passed: [ 'upgrade-bosh-and-kubo-<%= iaas %>' ]
    - get: gcs-bosh-creds
      passed: [ 'upgrade-bosh-and-kubo-<%= iaas %>' ]

  - task: unpack-tgz
    file: git-kubo-ci/tasks/unpack-tgz.yml
    tags: ['<%= iaas %>']
    input_mapping:
      source_tarball: new-kubo-deployment-tarball
    params:
      SOURCE_TARBALL_REGEX: kubo-deployment-*.tgz
      COLLAPSE_DIR: kubo-deployment

  - task: destroy-k8s
    tags: [<%= iaas %>]
    file: git-kubo-ci/tasks/destroy-k8s-instance.yml
    input_mapping:
      kubo-lock: kubo-lock-<%= iaas %>
      git-kubo-deployment: unpacked_dir


- name: destroy-bosh-<%= iaas %>
  plan:
  - aggregate:
    - get: git-kubo-ci
    - get: new-kubo-deployment-tarball
      passed: [ 'destroy-k8s-<%= iaas %>' ]
    - get: kubo-lock-<%= iaas %>
      version: every
      trigger: true
      passed: [ 'destroy-k8s-<%= iaas %>' ]
    - get: gcs-bosh-state
      passed: [ 'destroy-k8s-<%= iaas %>' ]
    - get: gcs-bosh-creds
      passed: [ 'destroy-k8s-<%= iaas %>' ]

  - task: unpack-tgz
    file: git-kubo-ci/tasks/unpack-tgz.yml
    tags: [ '<%= iaas %>' ]
    input_mapping:
      source_tarball: new-kubo-deployment-tarball
    params:
      SOURCE_TARBALL_REGEX: kubo-deployment-*.tgz
      COLLAPSE_DIR: kubo-deployment

  - task: destroy
    tags: [ '<%= iaas %>' ]
    file: git-kubo-ci/tasks/destroy-bosh.yml
    input_mapping:
      kubo-lock: kubo-lock-<%= iaas %>
      git-kubo-deployment: unpacked_dir

  - put: kubo-lock-<%= iaas %>
    params:
      release: kubo-lock-<%= iaas %>
<% end %>
