pins:
  stemcell_version: &stemcell_version "3468.13"
groups: []
resources:
- name: kubo-etcd-release
  type: github-release
  source:
    owner: pivotal-cf-experimental
    repository: kubo-etcd
    access_token: ((github-kubo-gitbot-access-token))
- name: docker-boshrelease
  type: bosh-io-release
  source:
    repository: cf-platform-eng/docker-boshrelease
- name: cf-mysql-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/cf-mysql-release
- name: uaa-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/uaa-release
- name: syslog-migration-release
  type: github-release
  source:
    owner: pivotal-cf
    repository: syslog-migration-release
    access_token: ((github-kubo-gitbot-access-token))
- name: compiled-releases
  type: gcs
  source:
    bucket: kubo-public
    json_key: ((gcs-json-key))
    regexp: .*-(\d+).tgz
- name: kubo-ci
  type: git
  source:
    branch: master
    uri: https://github.com/pivotal-cf-experimental/kubo-ci
- name: git-kubo-deployment
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry-incubator/kubo-deployment
- name: backup-and-restore-sdk-release
  type: github-release
  source:
    owner: cloudfoundry-incubator
    repository: backup-and-restore-sdk-release
    access_token: ((github-kubo-gitbot-access-token))
resource_types:
- name: gcs
  type: docker-image
  source:
    repository: frodenas/gcs-resource
jobs:
- name: compile-docker-release-ubuntu-trusty
  plan:
  - aggregate:
    - get: kubo-ci
    - get: git-kubo-deployment
    - get: docker-boshrelease
      trigger: true
  - task: export-release
    privileged: true
    file: kubo-ci/tasks/export-release.yml
    input_mapping:
      release: docker-boshrelease
      stemcell: ubuntu-trusty
  - put: compiled-releases
    params:
      file: compiled-release/*.tgz
- name: compile-kubo-etcd-release-ubuntu-trusty
  plan:
  - aggregate:
    - get: kubo-ci
    - get: git-kubo-deployment
    - get: kubo-etcd-release
      trigger: true
  - task: export-release
    privileged: true
    file: kubo-ci/tasks/export-release.yml
    input_mapping:
      release: kubo-etcd-release
      stemcell: ubuntu-trusty
  - put: compiled-releases
    params:
      file: compiled-release/*.tgz
- name: compile-cf-mysql-release-ubuntu-trusty
  plan:
  - aggregate:
    - get: kubo-ci
    - get: git-kubo-deployment
    - get: cf-mysql-release
      trigger: true
  - task: export-release
    privileged: true
    file: kubo-ci/tasks/export-release.yml
    input_mapping:
      release: cf-mysql-release
      stemcell: ubuntu-trusty
  - put: compiled-releases
    params:
      file: compiled-release/*.tgz
- name: compile-uaa-release-ubuntu-trusty
  plan:
  - aggregate:
    - get: kubo-ci
    - get: git-kubo-deployment
    - get: uaa-release
      trigger: true
  - task: export-release
    privileged: true
    file: kubo-ci/tasks/export-release.yml
    input_mapping:
      release: uaa-release
      stemcell: ubuntu-trusty
  - put: compiled-releases
    params:
      file: compiled-release/*.tgz

- name: compile-syslog-migration-release-ubuntu-trusty
  plan:
  - aggregate:
    - get: kubo-ci
    - get: git-kubo-deployment
    - get: syslog-migration-release
      trigger: true
  - task: export-release
    privileged: true
    file: kubo-ci/tasks/export-release.yml
    input_mapping:
      release: syslog-migration-release
      stemcell: ubuntu-trusty
  - put: compiled-releases
    params:
      file: compiled-release/*.tgz

- name: compile-backup-and-restore-sdk-release-ubuntu-trusty
  plan:
  - aggregate:
    - get: kubo-ci
    - get: git-kubo-deployment
    - get: backup-and-restore-sdk-release
      trigger: true
  - task: export-release
    privileged: true
    file: kubo-ci/tasks/export-release.yml
    input_mapping:
      release: backup-and-restore-sdk-release
      stemcell: ubuntu-trusty
  - put: compiled-releases
    params:
      file: compiled-release/*.tgz
      
