pins:
  stemcell_version: &stemcell_version "3468.5"
groups: []
resources:
- name: ubuntu-trusty
  type: bosh-io-stemcell
  source:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
- name: kubo-etcd-release
  type: github-release
  source:
    owner: pivotal-cf-experimental
    repository: kubo-etcd
- name: docker-boshrelease
  type: bosh-io-release
  source:
    repository: cf-platform-eng/docker-boshrelease
- name: compiled-releases
  type: gcs
  source:
    bucket: kubo-public
    json_key: ((gcs-json-key))
    regexp: .*-(\d+).tgz
- name: kubo-ci
  type: git
  source:
    branch: master
    uri: https://github.com/pivotal-cf-experimental/kubo-ci
resource_types:
- name: gcs
  type: docker-image
  source:
    repository: frodenas/gcs-resource
jobs:
- name: compile-docker-release-ubuntu-trusty
  plan:
  - aggregate:
    - get: kubo-ci
    - get: docker-boshrelease
      version:
        version: 30.1.3
    - get: ubuntu-trusty
      version:
        version: *stemcell_version
  - task: export-release
    privileged: true
    file: kubo-ci/tasks/export-release.yml
    input_mapping:
      release: docker-boshrelease
      stemcell: ubuntu-trusty
  - put: compiled-releases
    params:
      file: compiled-release/*.tgz
- name: compile-kubo-etcd-release-ubuntu-trusty
  plan:
  - aggregate:
    - get: kubo-ci
    - get: kubo-etcd-release
    - get: ubuntu-trusty
      version:
        version: *stemcell_version
  - task: export-release
    privileged: true
    file: kubo-ci/tasks/export-release.yml
    input_mapping:
      release: kubo-etcd-release
      stemcell: ubuntu-trusty
  - put: compiled-releases
    params:
      file: compiled-release/*.tgz
