resource_types:
- name: gcs
  type: docker-image
  source:
    repository: frodenas/gcs-resource

resources:
- name: kubo-ci
  type: git
  source:
    uri: https://github.com/pivotal-cf-experimental/kubo-ci
    branch: master
- name: docker-boshrelease
  type: bosh-io-release
  source:
    repository: cf-platform-eng/docker-boshrelease

- name: ubuntu-trusty-3421-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent

- name: compiled-releases
  type: gcs
  source:
    json_key: ((gcs-json-key))
    bucket: kubo-public
    regexp: ".*-(\\d+).tgz"

jobs:
- name: compile-docker-release-ubuntu-trusty-3421
  plan:
    - aggregate:
      - get: kubo-ci
      - get: docker-boshrelease
        version:
          # url: http://bosh.io/d/github.com/cf-platform-eng/docker-boshrelease?v=28.0.1
          version: "28.0.1"
      - get: ubuntu-trusty-3421-stemcell
        version:
          version: "3421.11"
    - task: export-release
      file: kubo-ci/tasks/export-release.yml
      privileged: true
      input_mapping:
        stemcell: ubuntu-trusty-3421-stemcell
        release: docker-boshrelease
    - put: compiled-releases
      params:
        file: "compiled-release/*.tgz"
