resources:
- name: git-kubo-deployment
  type: git
  source:
    uri: git@github.com:cloudfoundry-incubator/kubo-deployment.git
    branch: test-update-stemcell
    private_key: ((git-ssh-key))

- name: git-kubo-ci
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/kubo-ci
    branch: master

- name: gcp-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-google-kvm-ubuntu-trusty-go_agent
    version_family: 3468.latest

jobs:
- name: update-stemcell
  plan:
  - get: git-kubo-deployment
  - get: git-kubo-ci
  - get: gcp-stemcell
    trigger: true
  - task: update-manifest
    config:
      platform: linux
      inputs:
      - name: git-kubo-deployment
      - name: git-kubo-ci
      - name: gcp-stemcell
      outputs:
      - name: git-kubo-deployment-with-updated-stemcell
      run:
        path: ./git-kubo-ci/scripts/update-stemcell.sh
      image_resource:
        type: docker-image
        source:
          repository: pcfkubo/kubo-ci
          tag: stable
  - put: git-kubo-deployment
    params: { repository: git-kubo-deployment-with-updated-stemcell }
