resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: git-kubo-ci
  type: git
  source:
    uri: git@github.com:pivotal-cf-experimental/kubo-ci.git
    branch: master
    private_key: ((git-ssh-key))

- name: git-kubo-deployment
  type: git
  source:
    uri: git@github.com:cloudfoundry-incubator/kubo-deployment.git
    branch: master
    private_key: ((git-ssh-key))
    ignore_paths:
    - 'LICENSE'
    - 'NOTICE'

- name: git-kubo-home
  type: git
  source:
    uri: git@github.com:pivotal-cf-experimental/kubo-home.git
    private_key: ((git-ssh-key))

- name: git-kubo-release
  type: git
  source:
    uri: git@github.com:cloudfoundry-incubator/kubo-release.git
    branch: master
    private_key: ((git-ssh-key))
    ignore_paths:
    - '*.md'
    - 'LICENSE'
    - 'NOTICE'

- name: slack-failure
  type: slack-notification
  source:
    url: https://hooks.slack.com/services/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

jobs:
- name: run-unit-tests
  plan:
  - get: git-kubo-ci
  - get: git-kubo-deployment
    trigger: true
  - get: git-kubo-home
  - get: git-kubo-release
    trigger: true
  - task: run-release-unit-tests
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: pcfkubo/kubo-ci
          tag: stable
      run:
        path: 'true'
    on_success:
      do:
      - task: consolidate-inputs
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: pcfkubo/kubo-ci
              tag: stable
          run:
            path: bash
            args:
            - -c
            - 'mkdir consolidated_inputs; cp -r git-kubo-release git-kubo-deployment git-kubo-ci consolidated_inputs'
          outputs:
          - name: consolidated_inputs
          inputs:
          - name: git-kubo-deployment
          - name: git-kubo-release
          - name: git-kubo-ci
      - task: configure-slack-notification
        file: git-kubo-ci/tasks/configure-slack-notification.yml
        input_mapping: {target-repos: consolidated_inputs}
        params:
          MESSAGE: Unit tests for kubo-release succeeded
      - put: slack-failure
        params:
          text_file: slack-notification/text
      - task: infinite-loop
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: pcfkubo/kubo-ci
              tag: stable
          run:
            path: bash
            args:
            - -c
            - while true; do echo foo > /dev/null; done