---
pins:
  - &CONCOURSE_VERSION {version: 3.4.1}
  - &GARDEN_RUNC_VERSION {version: 1.6.0}
  - &STEMCELL_VERSION {version: "3445.7"}
resource_types:
  - name: bosh-deployment
    type: docker-image
    source:
      repository: cloudfoundry/bosh-deployment-resource
resources:
  - name: vsphere-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-vsphere-esxi-ubuntu-trusty-go_agent

  - name: concourse-vsphere-deployment
    tags: [vsphere]
    type: bosh-deployment
    source:
      target: ((vsphere_director_internal_ip))
      client: admin
      client_secret: ((vsphere_admin_password))
      ca_cert: ((vsphere_director_ssl_ca))
      deployment: concourse-worker

  # - name: gcp-stemcell
  #   type: bosh-io-stemcell
  #   source:
  #     name: bosh-google-kvm-ubuntu-trusty-go_agent

  # - name: concourse-gcp-deployment
  #   tags: [gcp]
  #   type: bosh-deployment
  #   source:
  #     target: ((gcp_director_internal_ip))
  #     client: admin
  #     client_secret: ((gcp_admin_password))
  #     ca_cert: ((gcp_director_ssl_ca))
  #     deployment: concourse-worker

  - name: concourse-release
    type: bosh-io-release
    source:
      repository: concourse/concourse

  - name: garden-runc-release
    type: bosh-io-release
    source:
      repository: cloudfoundry/garden-runc-release


jobs:
  - name: deploy-concourse-workers-vsphere
    plan:
      - aggregate:
        - get: concourse-release
          version: *CONCOURSE_VERSION
        - get: garden-runc-release
          version: *GARDEN_RUNC_VERSION

        - get: vsphere-stemcell
          version: *STEMCELL_VERSION
        - get: concourse-vsphere-deployment
          tags: [vsphere]

      - put: concourse-vsphere-deployment
        tags: [vsphere]
        params:
          manifest: concourse-vsphere-deployment/manifest.yml
          releases:
            - concourse-release/*.tgz
            - garden-runc-release/*.tgz
          stemcells:
            - vsphere-stemcell/*.tgz

  # - name: deploy-concourse-workers-gcp
  #   plan:
  #     - aggregate:
  #       - get: concourse-release
  #         version: *CONCOURSE_VERSION
  #       - get: garden-runc-release
  #         version: *GARDEN_RUNC_VERSION

  #       - get: gcp-stemcell
  #         version: *STEMCELL_VERSION
  #       - get: concourse-gcp-deployment
  #         tags: [gcp]

  #     - put: concourse-gcp-deployment
  #       tags: [gcp]
  #       params:
  #         manifest: concourse-gcp-deployment/manifest.yml
  #         releases:
  #           - concourse-release/*.tgz
  #           - garden-runc-release/*.tgz
  #         stemcells:
  #           - gcp-stemcell/*.tgz
