---
pins:
  - &CONCOURSE_VERSION {version: 3.4.1}
  - &GARDEN_RUNC_VERSION {version: 1.6.0}
  - &STEMCELL_VERSION {version: "3445.2"}
source_types:
  - name: bosh-deployment
    type: docker-image
    source:
      repository: cloudfoundry/bosh-deployment-resource
resources:
  - name: vsphere-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-vsphere-esxi-ubuntu-trusty-go_agent
  - name: concourse-vsphere-deployment
    type: bosh-deployment
    source:
      target: ((vsphere_concourse_bosh_director))
      client: ((vsphere_concourse_bosh_username))
      client_secret: ((vsphere_concourse_bosh_password))
      deployment: concourse-worker
- name: concourse-release
  type: bosh-io-release
  source:
    repository: concourse/concourse

- name: garden-runc-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/garden-runc-release
jobs:
  - name: deploy-concourse-workers-vsphere
    plan:
      - aggregate:
        - get: concourse-release
          version: *CONCOURSE_VERSION
        - get: garden-runc-release
          version: *GARDEN_RUNC_VERSION
        - get: git-kubo-ci
        - get: vsphere-stemcell
          version: *STEMCELL_VERSION
        - get: bosh-init-director-deployment-vsphere
          passed: [bosh-init-director-vsphere]
        - put: concourse-vsphere-deployment
          tags: [vsphere]
          params:
            manifest: git-kubo-ci/concourse/vsphere/workers.yml
            releases:
              - concourse-release/*.tgz
              - garden-runc-release/*.tgz
            stemcells:
              - vsphere-stemcell/*.tgz
