---
pins:
  - &CONCOURSE_VERSION {version: 3.4.1}
  - &GARDEN_RUNC_VERSION {version: 1.6.0}
  - &STEMCELL_VERSION {version: "3445.7"}
resource_types:
  - name: bosh-deployment
    type: docker-image
    source:
      repository: cloudfoundry/bosh-deployment-resource
resources:
  - name: vsphere-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-vsphere-esxi-ubuntu-trusty-go_agent

  - name: concourse-vsphere-deployment
    type: bosh-deployment
    source:
      target: 10.74.42.5
      client: admin
      client_secret: ((admin_password))
      ca_cert: ((director_ssl.ca))
      deployment: concourse-worker

  - name: concourse-release
    type: bosh-io-release
    source:
      repository: concourse/concourse

  - name: garden-runc-release
    type: bosh-io-release
    source:
      repository: cloudfoundry/garden-runc-release
  - name: git-kubo-ci
    type: git
    source:
      uri: https://github.com/pivotal-cf-experimental/kubo-ci
      branch: master

jobs:
  - name: deploy-concourse-workers-vsphere
    plan:
      - aggregate:
        - get: concourse-release
          version: *CONCOURSE_VERSION
        - get: garden-runc-release
          version: *GARDEN_RUNC_VERSION

        - get: vsphere-stemcell
          version: *STEMCELL_VERSION
        - get: git-kubo-ci
      - put: concourse-vsphere-deployment
        tags: [vsphere]
        params:
          dry_run: true
          manifest: git-kubo-ci/concourse/vsphere/workers.yml
          releases:
            - concourse-release/*.tgz
            - garden-runc-release/*.tgz
          stemcells:
            - vsphere-stemcell/*.tgz
          vars_files:
          - git-kubo-ci/concourse/vsphere/director.yml
          vars:
            worker-key:
              private_key: ((worker-key.private_key))
            tsa-host-key:
              public_key: ((tsa-host-key.public_key))