resources:
- name: git-kubo-ci
  type: git
  source:
    uri: https://github.com/pivotal-cf-experimental/kubo-ci
    branch: master
    paths:
    - src/vsphere-cleaner/*

jobs:
- name: tests
  plan:
  - aggregate:
    - get: git-kubo-ci
      trigger: true
  - task: run-tests
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: pcfkubo/kubo-ci
          tag: stable
      inputs:
      - name: git-kubo-ci
      run:
        path: git-kubo-ci/src/vsphere-cleaner/run-tests
