---
name: turbulence

releases:
- name: turbulence
  url: "https://storage.googleapis.com/kubo-pipeline-store/turbulence-release-0.10.0%2Bdev.1.tgz"
  sha1: "0321099d5399da2c002459c4d5817a273c6ae3c7"
  version: "0.10.0+dev.1"

stemcells:
- alias: default
  os: ubuntu-xenial
  version: latest

instance_groups:
- name: api
  instances: 1
  azs: [z1]
  jobs:
  - name: turbulence_api
    release: turbulence
    provides:
      api: {shared: true}
    properties:
      password: ((turbulence_api_password))
      cert: ((turbulence_api_cert))
      director:
        host: ((director_ip))
        cert:
          ca: ((director_ssl.ca))
        client: ((director_client))
        client_secret: ((director_client_secret))
  vm_type: default
  stemcell: default
  networks:
  - name: default
    static_ips: [((turbulence_api_ip))]

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 5000-20000
  update_watch_time: 5000-20000

variables:
- name: turbulence_api_password
  type: password
- name: turbulence_api_ca
  type: certificate
  options:
    is_ca: true
    common_name: turbulence_api_ca
- name: turbulence_api_cert
  type: certificate
  options:
    ca: turbulence_api_ca
    common_name: ((turbulence_api_ip))
    alternative_names:
    - ((turbulence_api_ip))
    - "*.api.default.turbulence.bosh" # todo
