---
releases:
- name: turbulence
  url: "https://storage.googleapis.com/kubo-pipeline-store/turbulence-release-0.10.0%2Bdev.1.tgz"
  sha1: "0321099d5399da2c002459c4d5817a273c6ae3c7"
  version: "0.10.0+dev.1"

addons:
- name: turbulence_agent
  jobs:
  - name: turbulence_agent
    release: turbulence
    consumes:
      api:
        instances:
        - address: ((internal_ip))
        properties:
          advertised_host: ""
          username: turbulence
          password: ((turbulence_api_password))
          agent_listen_port: 8081
          cert:
            ca: ((turbulence_api_ssl.ca))
