platform: linux
image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    tag: stable

run:
  path: git-kubo-ci/scripts/apply-runtime-config.sh
  args:
  - 'kubo-lock/metadata'
  - 'gcs-bosh-creds/creds.yml'

inputs:
- name: kubo-lock
- name: git-kubo-ci
- name: gcs-bosh-creds
