platform: linux
image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    tag: stable

run:
  path: git-kubo-ci/scripts/apply-cloud-config.sh
  args:
  - gcs-source-json/source.json

inputs:
- name: git-kubo-ci
- name: gcs-source-json
