platform: linux
image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    tag: stable

run:
  path: git-kubo-ci/scripts/apply-proxy-to-env.sh
inputs:

- name: kubo-lock
- name: git-kubo-deployment
- name: gcs-bosh-creds
- name: git-kubo-ci
outputs:
- name: kubo-lock-with-proxy
