platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    tag: stable

run:
  path: git-kubo-ci/scripts/setup-multiaz-aws.sh

params:
  DEPLOYMENT_NAME: ci-service

inputs:
  - name: git-kubo-ci
  - name: git-kubo-deployment
  - name: gcs-bosh-creds
  - name: kubo-lock-pre

outputs:
  - name: kubo-lock
