---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/main-bosh-docker

inputs:
- name: git-kubo-ci
- name: git-kubo-deployment

run:
  path: git-kubo-ci/scripts/run-k8s-in-dockercpi.sh
