---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    tag: stable

run:
  path: git-kubo-ci/scripts/build-environment-metadata.sh

params:
  CFCR_GENERAL: ~
  CFCR_IAAS: ~
  CFCR_ROUTING: ~
  CREDHUB_CA_CERT: ~
  CREDHUB_CLIENT: ~
  CREDHUB_SECRET: ~
  CREDHUB_SERVER: ~

inputs:
- name: git-kubo-ci
- name: kubo-lock

outputs:
- name: bosh-creds
- name: environment
