platform: linux
image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    tag: stable
run:
  path: git-kubo-ci/scripts/bump-boshrelease.sh
inputs:
  - name: git-kubo-ci
  - name: git-kubo-deployment
  - name: boshrelease

outputs:
  - name: git-kubo-deployment-output
