platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    tag: stable

run:
  path: git-kubo-ci/scripts/bump-release-golang.sh

inputs:
  - name: git-kubo-ci
  - name: release
  - name: golang-release
