platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    tag: stable

run:
  path: git-kubo-ci/scripts/bump-kubernetes-port.sh

params:
  BUMP_AMOUNT: ""

inputs:
- name: git-kubo-ci
- name: kubo-lock-pre

outputs:
- name: kubo-lock
