platform: linux
image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    tag: stable
params:
  ENV_NAME:
  POOL_NAME:
  LOCK_DIR:
inputs:
- name: kubo-lock-repo
- name: git-kubo-ci
outputs:
- name: modified-repo
run:
  path: git-kubo-ci/scripts/claim-lock-manually.sh
