platform: linux
image_resource:
  type: docker-image
  source:
    repository: pcfkubo/vsphere-cleaner
    tag: stable

inputs:
- name: kubo-lock-repo
- name: git-kubo-ci

params:
  ENV_NAME:
  POOL_NAME:
run:
  path: bash
  args:
  - -ec
  - vsphere-cleaner "kubo-lock-repo/$POOL_NAME/claimed/$ENV_NAME"
