platform: linux
image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    tag: stable

inputs:
- name: kubo-lock
- name: git-kubo-ci

params:
  ENV_FILE:
run:
  path: git-kubo-ci/scripts/cleanup-environment.sh
