platform: linux
image_resource:
  type: docker-image
  source:
    repository: google/cloud-sdk
    tag: stable
run:
  path: git-kubo-ci/scripts/cleanup-gcp-disks.sh
params:
  GCP_SERVICE_ACCOUNT: ""

inputs:
  - name: git-kubo-ci

