platform: linux
image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    tag: stable

inputs:
- name: kubo-lock-repo
- name: git-kubo-ci

params:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  AWS_DEFAULT_REGION:
  ENV_NAME:

run:
  path: git-kubo-ci/scripts/cleanup-environment.sh
