platform: linux
image_resource:
  type: docker-image
  source:
    repository: pcfkubo/cf-cli
    tag: stable

inputs:
- name: kubo-lock
- name: git-kubo-ci

params:
  ENV_FILE:
  ENV_NAME:
  CF_PASSWORD:
run:
  path: ./git-kubo-ci/scripts/cleanup-cf.sh