platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    tag: stable

inputs:
- name: git-kubo-ci
- name: kubo-lock
- name: gcs-bosh-creds

outputs:
- name: kdrats-config

params:
  BOSH_DEPLOYMENT:
  CREDFILE:
  VARFILE:
run:
  path: git-kubo-ci/scripts/create-kdrats-config.sh
