platform: linux
image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    tag: stable
run:
  path: git-kubo-ci/scripts/upload-github-releases.sh

params:
  ACCESS_KEY_ID: ""
  SECRET_ACCESS_KEY: ""
  BRANCH: "master"

inputs:
  - name: git-kubo-ci
  - name: git-kubo-deployment-output
  - name: kubo-version
outputs:
  - name: kubo-deployment
