platform: linux
image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    tag: stable
run:
  path: git-kubo-ci/scripts/delay-execution.sh

inputs:
  - name: git-kubo-ci

params:
  DELAY_TIME_SECS:
