platform: linux
image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    tag: stable

run:
  path: git-kubo-ci/scripts/destroy-k8s-instance.sh

params:
  DEPLOYMENT_NAME: ci-service

inputs:
  - name: git-kubo-ci
  - name: gcs-bosh-creds
  - name: git-kubo-deployment
  - name: kubo-lock
