platform: linux
image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    tag: stable
run:
  path: git-kubo-ci/scripts/destroy-k8s-instance.sh

inputs:
  - name: git-kubo-ci
  - name: s3-bosh-creds
  - name: git-kubo-deployment
  - name: kubo-lock
