platform: linux
image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    tag: stable
run:
  path: git-kubo-ci/scripts/finalize-kubo-release.sh


params:
  ACCESS_KEY_ID: ""
  SECRET_ACCESS_KEY: ""

inputs:
  - name: git-kubo-ci
  - name: git-kubo-deployment
  - name: git-kubo-release
  - name: kubo-version
  - name: gcs-kubo-release-tarball
outputs:
  - name: kubo-release
  - name: git-kubo-release-output
    path: git-kubo-release