platform: linux
image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    tag: stable
run:
  path: git-kubo-ci/scripts/generate-director-yml.yml

params:
  env:

inputs:
  - name: git-kubo-ci
  - name: git-kubo-deployment
  - name: gcs-bosh-creds
  - name: kubo-lock

outputs:
  - name: generated-config
