platform: linux
image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    tag: stable
params:
  PR_STATUS:
  PR_REPO: kubo-release
run:
  path: git-kubo-ci/scripts/generate-pr-message.sh

inputs:
- name: git-kubo-ci
- name: git-kubo-release
outputs:
- name: pr-slack-message
