---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    tag: stable

run:
  path: git-kubo-ci/scripts/get-bosh-secrets.sh

params:
  CREDHUB_SECRET:
  CREDHUB_SERVER:
  CREDHUB_CLIENT:
  CREDHUB_CA_CERT:

inputs:
- name: git-kubo-ci
- name: kubo-lock

outputs:
- name: bosh-creds
- name: updated-kubo-lock
