platform: linux
image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    tag: stable
run:
  path: git-kubo-ci/scripts/install-common-bosh.sh
params:
  GCP_SERVICE_ACCOUNT:
  CREDHUB_SECRET:
  CREDHUB_SERVER:
  CREDHUB_CLIENT:
  CREDHUB_CA_CERT:

inputs:
- name: git-kubo-ci
- name: git-kubo-deployment
- name: kubo-lock
