platform: linux
image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    tag: stable

inputs:
- name: git-kubo-ci
- name: kubo-lock-gcp-lifecycle

run:
  path: git-kubo-ci/scripts/recycle-cleanup-gcp.sh
