platform: linux
image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    tag: stable
run:
  path: git-kubo-ci/scripts/run-conformance-tests.sh

params:
  DEPLOYMENT_NAME: ci-service

inputs:
  - name: git-kubo-ci
  - name: gcs-bosh-creds
  - name: kubo-lock
  - name: git-kubo-deployment

outputs:
  - name: conformance-results
