platform: linux
image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    tag: stable
run:
  path: git-kubo-ci/scripts/run-k8s-upgrade-tests.sh
params:
  CLOUD_CONFIG_OPS_FILE:

inputs:
- name: git-kubo-ci
- name: git-kubo-deployment
- name: kubo-lock
- name: gcs-bosh-state
- name: gcs-bosh-creds
- name: gcs-kubo-release-tarball
- name: gcs-kubeconfig
- name: new-bosh-stemcell

outputs:
- name: bosh-state
- name: bosh-creds
