platform: linux
image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    image-id: 90e9c6091a57e45106712c50a6d2225b359c56d81c72021123439004ab515e5b
inputs:
- name: git-kubo-ci
- name: git-kubo-deployment
- name: gcs-bosh-creds
- name: kubo-lock
params:
  DEPLOYMENT_NAME: ci-service
  KUBO_ENVIRONMENT_DIR: "/temporary"
run:
  path: ./git-kubo-ci/scripts/run-istio-tests.sh
