platform: linux
image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    tag: stable
run:
  path: git-kubo-ci/scripts/run-k8s-integration-tests.sh

params:
  DEPLOYMENT_NAME: ci-service
  ENABLE_MULTI_AZ_TESTS: false
  ENABLE_OSS_ONLY_TESTS: false
  ENABLE_PERSISTENT_VOLUME_TESTS: false
  ENABLE_K8S_LBS_TESTS: false
  CIDR_VARS_FILE:

inputs:
  - name: git-kubo-ci
  - name: git-kubo-deployment
  - name: gcs-bosh-creds
  - name: kubo-lock
