platform: linux
image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    tag: stable
inputs:
- name: istio-release
- name: git-kubo-ci
- name: git-kubo-deployment
- name: gcs-bosh-creds
- name: kubo-lock
params:
  DEPLOYMENT_NAME: ci-service
  KUBO_ENVIRONMENT_DIR: "/temporary"
run:
  path: ./git-kubo-ci/scripts/run-istio-tests.sh
