platform: linux
image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    tag: stable

inputs:
- name: gcs-slack-watcher-list
outputs:
- name: gcs-slack-watcher-list

run:
  path: /bin/bash
  args:
  - -exc
  - |
    cat gcs-slack-watcher-list/slack-watcher-list.txt | sed '1,1{H;1h;d;};$G' > gcs-slack-watcher-list/slack-watcher-list.txt
    mkdir slack-message
    echo "==> The OSS watcher for this week is !$(head -1 gcs-slack-watcher-list/slack-watcher-list.txt)" > slack-message/announcement.txt