platform: linux
image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    tag: stable

inputs:
- name: gcs-slack-watcher-list
outputs:
- name: slack-watcher-list-out
- name: slack-message

run:
  path: /bin/bash
  args:
  - -exc
  - |
    cat gcs-slack-watcher-list/slack-watcher-list.txt | sed '1,1{H;1h;d;};$G' > slack-watcher-list-out/slack-watcher-list.txt
    echo "==> The OSS watcher for this week is <@$(head -1 slack-watcher-list-out/slack-watcher-list.txt | tr -d '\n')> <==" > slack-message/announcement.txt