platform: linux
image_resource:
  type: docker-image
  source:
    repository: concourse/git-resource
    tag: latest
params:
  ENV_NAME:
  POOL_NAME:
  LOCK_DIR:
inputs:
- name: kubo-lock-repo
- name: git-kubo-ci
outputs:
- name: modified-repo
run:
  path: git-kubo-ci/scripts/unclaim-lock-manually.sh
