platform: linux
image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    tag: stable
run:
  path: /bin/bash
  args:
  - -exc
  - |
    tar -xzf  gcs-kubo-deployment-release/kubo-deployment-*.tgz
    mv kubo-deployment-*/kubo-deployment/* git-kubo-deployment/
inputs:
- name: gcs-kubo-deployment-release
outputs:
- name: git-kubo-deployment
