platform: linux
image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    tag: stable
run:
  path: /bin/bash
  args:
  - -exc
  - |
    tar -xzf  "source_tarball/$SOURCE_TARBALL_REGEX" -C unpacked_dir/

inputs:
- name: source_tarball
outputs:
- name: unpacked_dir

params:
  SOURCE_TARBALL_REGEX: replace-me