platform: linux
image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    tag: stable
inputs:
- name: git-kubo-ci
- name: git-kubo-deployment
- name: kubo-lock
- name: gcs-bosh-creds
outputs:
- name: kubeconfig
params:
  KUBO_ENVIRONMENT_DIR: "environment/"
  DEPLOYMENT_NAME: "ci-service"
run:
  path: /bin/bash
  args:
  - -ex
  - -c
  - |
    mkdir -p "${KUBO_ENVIRONMENT_DIR}"
    source "./git-kubo-ci/scripts/lib/utils.sh"
    setup_env "${KUBO_ENVIRONMENT_DIR}"
    cp ~/.kube/config kubeconfig/config
