platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    tag: stable

run:
  path: git-kubo-ci/scripts/update-kubernetes-port.sh

params:
  PORT_NUMBER: ""

inputs:
- name: git-kubo-ci
- name: kubo-lock-pre

outputs:
- name: kubo-lock
