platform: linux
image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    tag: stable
run:
  path: git-kubo-ci/scripts/upload-release.sh

inputs:
  - name: git-kubo-ci
  - name: release
  - name: source-json
