platform: linux
image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    tag: stable
run:
  path: git-kubo-ci/scripts/upload-artefacts.sh

params:

inputs:
  - name: git-kubo-ci
  - name: gcs-kubo-deployment-tarball-untested
  - name: kubo-lock