---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci

inputs:
- name: gcs-bosh-creds
- name: git-kubo-ci
- name: git-kubo-deployment
- name: kubo-lock

run:
  path: git-kubo-ci/scripts/upload-stemcell.sh

params:
  IAAS:
