---
azs:
- name: z1
  cloud_properties:
    zone: ((zone))

networks:
- name: public
  type: dynamic
  subnets:
  - az: z1
    cloud_properties:
      network_name: ((network))
      subnetwork_name: ((subnetwork))
      ephemeral_external_ip: true

vm_types:
- name: common
  cloud_properties:
    machine_type: n1-standard-1
    root_disk_size_gb: 20
    root_disk_type: pd-ssd
    tags: [ 'internal', 'ssh-in' ]

disk_types:
- name: 10240
  disk_size: 10240
- name: 5120
  disk_size: 5120

compilation:
  workers: 4
  network: public
  az: z1
  reuse_compilation_vms: true
  vm_type: common
