---
## Controls Files.
# These are YAML files that hold all the details for running checks.
#
## Uncomment to use different control file paths.
# masterControls: ./cfg/master.yaml
# nodeControls: ./cfg/node.yaml
# federatedControls: ./cfg/federated.yaml

master:
  components:
    - apiserver
    - scheduler
    - controllermanager
    - etcd
    - flanneld
    - kubernetes

  kubernetes:
    defaultconf: /etc/kubernetes/config

  apiserver:
    bins:
      - "kube-apiserver"

  scheduler:
    bins:
      - "kube-scheduler"

  controllermanager:
    bins:
      - "kube-controller-manager"

  etcd:
    optional: true
    bins:
      - "etcd"
    confs:
      - /var/vcap/jobs/etcd/config/etcd_link.json

  flanneld:
    optional: true
    bins:
      - flanneld


node:
  components:
    - kubelet
    - proxy
    - kubernetes

  kubernetes:
    defaultconf: /etc/kubernetes/config

  kubelet:
    bins:
      - "hyperkube kubelet"
      - "kubelet"

  proxy:
    bins:
      - "kube-proxy"
      - "hyperkube proxy"
      - "proxy"

federated:
  components:
    - fedapiserver
    - fedcontrollermanager

  fedapiserver:
    bins:
      - "hyperkube federation-apiserver"
      - "kube-federation-apiserver"
      - "federation-apiserver"

  fedcontrollermanager:
    bins:
      - "hyperkube federation-controller-manager"
      - "kube-federation-controller-manager"
      - "federation-controller-manager"
