- type: replace
  path: /resources/-
  value:
    name: stemcell-gcp
    type: bosh-io-stemcell
    source:
      name: bosh-google-kvm-ubuntu-xenial-go_agent

- type: replace
  path: /jobs/name=deploy-k8s/plan/put=cfcr-deployment/params/ops_files/-
  value: git-kubo-deployment/manifests/ops-files/iaas/gcp/cloud-provider.yml
- type: replace
  path: /jobs/name=deploy-k8s/plan/put=cfcr-deployment/params/ops_files/-
  value: git-kubo-deployment/manifests/ops-files/iaas/gcp/add-subnetwork-for-internal-load-balancer.yml
- type: replace
  path: /jobs/name=deploy-k8s/plan/put=cfcr-deployment/params/ops_files/-
  value: git-kubo-deployment/manifests/ops-files/use-vm-extensions.yml
