internal_ip: # Internal ip address of the BOSH director. Please select an available ip address in the network you wish to deploy into.

internal_cidr: # CIDR range that BOSH will deploy to
internal_gw: # internal gateway

director_name: # user friendly Director name
dns_recursor_ip: # DNS IP address for resolving non-BOSH hostnames

kubo_release_url: https://storage.googleapis.com/kubo-public/kubo-release-latest.tgz

worker_count: 3

# Kubernetes OIDC settings
# https://kubernetes.io/docs/admin/authentication/#configuring-the-api-server
# oidc_issuer_url:
# oidc_client_id:
# oidc_username_claim:
# oidc_username_prefix:
# oidc_groups_claim:
# oidc_groups_prefix:
# oidc_ca:

# uncomment these fields to configure proxy settings for docker
# http_proxy: # e.g. http://my.proxy.local:73636
# https_proxy: # e.g. https://secure.proxy.local:5566
# no_proxy: # e.g. '1.2.3.4,2.3.4.5'
