platform: linux
image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    tag: stable
inputs:
  - name: modified-release
run:
  dir: modified-release
  path: bosh
  args:
  - create-release
  - --force
