## ConfigMap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-configmap
  labels:
    name: test-configmap-secrets
data:
  cartoons.json: |
    {"sponge": "bob"}

## Secret
---
apiVersion: v1
kind: Secret
metadata:
  name: test-secret
  labels:
    name: test-configmap-secrets
type: Opaque
data:
  cartoons.json: eyJrcmFiYnktcGF0dHktc2VjcmV0LWZvcm11bGEiOiJjcmFicyJ9Cg==

## Deployment
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: test-configmap-secrets
    spec:
      containers:
      - name: busybox-with-configmaps-and-secrets
        image: busybox
        command: ['sh', '-c', 'echo Hello Kubernetes! && while :; do sleep 300; done']
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: test-configmap-volume
          mountPath: /tmp/configmap
        - name: test-secret-volume
          mountPath: /tmp/secrets
      volumes:
      - name: test-configmap-volume
        configMap:
          name: test-configmap
      - name: test-secret-volume
        secret:
          secretName: test-secret
