azs:
- name: z1
  cloud_properties: {zone: europe-west1-b}

vm_types:
- name: minimal
  cloud_properties:
    machine_type: n1-standard-1
    root_disk_size_gb: 20
    root_disk_type: pd-ssd
    tags:
    - no-ip
    - internal
- name: master
  cloud_properties:
    machine_type: n1-standard-1
    root_disk_size_gb: 20
    root_disk_type: pd-ssd
    service_account: gaffer-kubo-master@cf-pcf-kubo.iam.gserviceaccount.com
    tags:
    - no-ip
    - internal
    target_pool: gaffer-kubo-tcp-public
- name: worker
  cloud_properties:
    machine_type: n1-standard-2
    root_disk_size_gb: 100
    root_disk_type: pd-ssd
    service_account: gaffer-kubo-worker@cf-pcf-kubo.iam.gserviceaccount.com
    tags:
    - no-ip
    - internal
- name: concourse-worker
  cloud_properties:
    machine_type: n1-standard-1
    root_disk_size_gb: 200
    root_disk_type: pd-ssd
    service_account: gaffer-kubo@cf-pcf-kubo.iam.gserviceaccount.com
    tags:
    - no-ip
    - internal

networks:
- name: default
  type: dynamic
  subnets:
  - az: z1
    cloud_properties:
      ephemeral_external_ip: false
      network_name: gaffer
      subnetwork_name: gaffer-kubo-europe-west1
    dns:
    - 10.0.1.1
    gateway: 10.0.1.1
    range: 10.0.1.0/24

compilation:
  workers: 4
  reuse_compilation_vms: true
  az: z1
  network: default
  vm_type: worker
