instance_groups:
- azs: [z1, z2, z3]
  instances: 1
  jobs:
  - name: postgres
    release: postgres
  lifecycle: service
  name: db
  networks:
  - name: default
  persistent_disk_type: large
  properties:
    databases:
      port: 5432
      databases:
      - name: atc
      roles:
      - name: atc
        password: ((postgresql-password))
  stemcell: bosh-google-kvm-ubuntu-trusty-go_agent
  update:
    max_in_flight: 1
  vm_type: default
- azs: [z1, z2, z3]
  instances: 1
  jobs:
  - name: atc
    properties:
      basic_auth_username: kuboadmin
      basic_auth_password: ((kubo_admin_password))
      token_signing_key: ((token-signing-key))
      allow_self_signed_certificates: true
      github_auth:
        client_id: ((github-client-id))
        client_secret: ((github-client-secret))
        authorize:
          - organization: pivotal-cf-experimental
            teams: [ pcf-kubo ]
          - organization: cloudfoundry-incubator
            teams: [ cfcr, CFCR Core ]
          - organization: pivotal-cf
            teams: [ vmware-kubo, pks-releng  ]
          - user: lamlouis
      external_url: https://ci.kubo.sh
      tls_cert: ((atc-certificate.certificate))((atc-certificate.ca))
      tls_key: ((atc-certificate.private_key))
      tls_bind_port: 443
      bind_port: 80
      postgresql:
        database: atc
        role:
          name: atc
          password: ((postgresql-password))
      credhub:
        url: https://10.1.0.2:8844
        tls:
          insecure_skip_verify: true
        client_id: director_to_credhub
        client_secret: ((uaa_clients_director_to_credhub))
    release: concourse
  - name: tsa
    properties:
      token_signing_key: ((token-signing-key))
      host_key: ((tsa-host-key))
      host_public_key: ((tsa-host-key.public_key))
      authorized_keys:
      - ((worker-key.public_key))
    release: concourse
  lifecycle: service
  name: concourse
  networks:
  - default:
    - dns
    - gateway
    name: default
  persistent_disk_type: large
  properties: {}
  stemcell: bosh-google-kvm-ubuntu-trusty-go_agent
  update:
    max_in_flight: 1
  vm_type: default
  vm_extensions:
  - gcp-lb
- azs: [z1, z2, z3]
  instances: 1
  jobs:
  - name: worker
    release: concourse
    consumes:
      baggageclaim: {from: bc-gcp}
    properties:
      tags:
        - gcp
        - gcp-lb
      tsa:
        worker_key: ((worker-key))
        host_public_key: ((tsa-host-key.public_key))
  - name: baggageclaim
    release: concourse
    provides:
      baggageclaim: {as: bc-gcp}
  - name: garden
    release: garden-runc
    properties:
      garden:
        listen_address: 0.0.0.0:7777
        listen_network: tcp
  lifecycle: service
  name: worker-gcp
  networks:
  - name: default
  stemcell: bosh-google-kvm-ubuntu-trusty-go_agent
  update:
    max_in_flight: 1
  vm_type: large
- azs: [z1, z2, z3]
  instances: 2
  jobs:
  - name: worker
    release: concourse
    consumes:
      baggageclaim: {from: bc}
    properties:
      tsa:
        worker_key: ((worker-key))
        host_public_key: ((tsa-host-key.public_key))
  - name: baggageclaim
    release: concourse
    provides:
      baggageclaim: {as: bc}
  - name: garden
    release: garden-runc
    properties:
      garden:
        listen_address: 0.0.0.0:7777
        listen_network: tcp
  lifecycle: service
  name: worker
  networks:
  - name: default
  stemcell: bosh-google-kvm-ubuntu-trusty-go_agent
  update:
    max_in_flight: 1
  vm_type: large
name: kubo-ci
releases:
- name: concourse
  sha1: aaa4e4d42adb2293abc79422351ca71ed548f95c
  url: https://bosh.io/d/github.com/concourse/concourse?v=3.13.0
  version: 3.13.0
- name: garden-runc
  sha1: 54cbb89cae1be0708aa056185671665d7f4b2a4f
  url: https://bosh.io/d/github.com/cloudfoundry/garden-runc-release?v=1.13.1
  version: 1.13.1
- name: postgres
  version: 28
  sha1: c1fcec62cb9d2e95e3b191e3c91d238e2b9d23fa
  url: https://bosh.io/d/github.com/cloudfoundry/postgres-release?v=28
stemcells:
- alias: bosh-google-kvm-ubuntu-trusty-go_agent
  os: ubuntu-trusty
  version: latest
update:
  canaries: 1
  canary_watch_time: 30000-300000
  max_errors: 2
  max_in_flight: 1
  serial: true
  update_watch_time: 30000-300000

variables:
- name: kubo_admin_password
  type: password
- name: postgresql-password
  type: password
- name: token-signing-key
  type: rsa
