---
resources:
- name: git-kubo-ci
  type: git
  source:
    uri: https://github.com/pivotal-cf-experimental/kubo-ci
    branch: master
    paths:
    - docker-images/*

- name: kubo-ci-latest
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    tag: latest

- name: kubo-ci-stable
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    tag: stable
- name: gcs-vsphere-cleaner
  type: gcs
  source:
    json_key: {{gcs-json-key}}
    bucket: kubo-public
    versioned_file: vsphere-cleaner

resource_types:
- name: gcs
  type: docker-image
  source:
    repository: frodenas/gcs-resource

jobs:
- name: build-kubo-ci
  plan:
  - get: git-kubo-ci
    trigger: true
  - get: gcs-vsphere-cleaner
    trigger: true
  - put: kubo-ci-latest
    params:
      build: git-kubo-ci/docker-images
      cache: true
  - task: test-docker-image
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: pcfkubo/kubo-ci
          tag: latest

      inputs:
      - name: git-kubo-ci
      run:
        path: ginkgo
        args:
        - -r
        - git-kubo-ci/docker-images/system_tests/
  - put: kubo-ci-stable
    params:
      cache: true
      pull_repository: pcfkubo/kubo-ci
      pull_tag: latest
