<%
  tested_images=%w(test-runner vsphere-cleaner aws-maintenance kubo-ci)
  untested_images=%w(ulimit kubectl cf-cleaner git-bosh api-proxy)
%>
---
resources:
<% (tested_images + untested_images).each do |image_name| %>
- name: git-kubo-ci-<%= image_name %>
  type: git
  source:
    uri: https://github.com/pivotal-cf-experimental/kubo-ci
    branch: master
    paths:
    - docker-images/<%= image_name %>

- name: <%= image_name %>-stable
  type: docker-image
  source:
    repository: pcfkubo/<%= image_name %>
    email: ((docker-hub-email))
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    tag: stable

  <% if tested_images.include? image_name %>
- name: <%= image_name %>-latest
  type: docker-image
  source:
    repository: pcfkubo/<%= image_name %>
    email: ((docker-hub-email))
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    tag: latest
  <% end %>
<% end %>

- name: gcs-vsphere-cleaner
  type: gcs
  source:
    json_key: ((gcs-json-key))
    bucket: kubo-public
    versioned_file: vsphere-cleaner

resource_types:
- name: gcs
  type: docker-image
  source:
    repository: frodenas/gcs-resource

jobs:
- name: build-kubo-ci
  plan:
  - get: git-kubo-ci-kubo-ci
    trigger: true
  - put: kubo-ci-latest
    params:
      build: git-kubo-ci-kubo-ci/docker-images/kubo-ci
      cache: true
  - task: test-docker-image
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: pcfkubo/kubo-ci
          tag: latest

      inputs:
      - name: git-kubo-ci-kubo-ci
      run:
        path: ginkgo
        args:
        - -r
        - git-kubo-ci-kubo-ci/docker-images/kubo-ci/system_tests/
  - put: kubo-ci-stable
    params:
      cache: true
      pull_repository: pcfkubo/kubo-ci
      pull_tag: latest

- name: build-vsphere-cleaner
  plan:
  - get: git-kubo-ci-vsphere-cleaner
    trigger: true
  - get: gcs-vsphere-cleaner
    trigger: true
  - put: vsphere-cleaner-latest
    params:
      build: git-kubo-ci-vsphere-cleaner/docker-images/vsphere-cleaner
  - task: test-docker-image
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: pcfkubo/vsphere-cleaner
          tag: latest
      inputs:
      - name: git-kubo-ci-vsphere-cleaner
      run:
        path: git-kubo-ci-vsphere-cleaner/docker-images/vsphere-cleaner/run_tests
  - put: vsphere-cleaner-stable
    params:
      cache: true
      pull_repository: pcfkubo/vsphere-cleaner
      pull_tag: latest

- name: build-ulimit
  plan:
  - get: git-kubo-ci-ulimit
    trigger: true
  - put: ulimit-stable
    params:
      build: git-kubo-ci-ulimit/docker-images/ulimit

- name: build-test-runner
  plan:
  - get: git-kubo-ci-test-runner
    trigger: true
  - put: test-runner-latest
    params:
      build: git-kubo-ci-test-runner/docker-images/test-runner
  - task: test-docker-image
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: pcfkubo/test-runner
          tag: latest
      inputs:
      - name: git-kubo-ci-test-runner
      run:
        path: ginkgo
        args:
        - -r
        - git-kubo-ci-test-runner/docker-images/test-runner/system_tests
  - put: test-runner-stable
    params:
      cache: true
      pull_repository: pcfkubo/test-runner
      pull_tag: latest

- name: build-kubectl
  plan:
  - get: git-kubo-ci-kubectl
    trigger: true
  - put: kubectl-stable
    params:
      build: git-kubo-ci-kubectl/docker-images/kubectl

- name: build-cf-cleaner
  plan:
  - get: git-kubo-ci-cf-cleaner
    trigger: true
  - put: cf-cleaner-stable
    params:
      build: git-kubo-ci-cf-cleaner/docker-images/cf-cleaner

- name: build-git-bosh
  plan:
  - get: git-kubo-ci-git-bosh
    trigger: true
  - put: git-bosh-stable
    params:
      build: git-kubo-ci-git-bosh/docker-images/git-bosh

- name: build-aws-maintenance
  plan:
   - get: git-kubo-ci-aws-maintenance
     trigger: true
   - put: aws-maintenance-latest
     params:
       build: git-kubo-ci-aws-maintenance/docker-images/aws-maintenance
   - task: test-docker-image
     config:
       platform: linux
       image_resource:
         type: docker-image
         source:
           repository: pcfkubo/aws-maintenance
           tag: latest
       inputs:
       - name: git-kubo-ci-aws-maintenance
       run:
         path: git-kubo-ci-aws-maintenance/docker-images/aws-maintenance/run_tests
   - put: aws-maintenance-stable
     params:
       cache: true
       pull_repository: pcfkubo/aws-maintenance
       pull_tag: latest

- name: build-api-proxy
  plan:
  - get: git-kubo-ci-api-proxy
    trigger: true
  - put: api-proxy-stable
    params:
      build: git-kubo-ci-api-proxy/docker-images/api-proxy
