
name: concourse

releases:
- name: concourse
  sha1: aaa4e4d42adb2293abc79422351ca71ed548f95c
  url: https://bosh.io/d/github.com/concourse/concourse?v=3.13.0
  version: 3.13.0
- name: garden-runc
  sha1: 54cbb89cae1be0708aa056185671665d7f4b2a4f
  url: https://bosh.io/d/github.com/cloudfoundry/garden-runc-release?v=1.13.1
  version: 1.13.1

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: 3468.17

instance_groups:
- name: worker
  instances: 1
  vm_type: large
  vm_extensions:
  - 500GB_ephemeral_disk
  stemcell: trusty
  azs: [z1]
  networks: [{name: private}]
  jobs:
  - name: worker
    consumes: {baggageclaim: {from: worker-baggageclaim}}
    release: concourse
    properties:
      tags:
        - aws-lb
        - aws
      tsa:
        worker_key: ((worker-key))
        host: ci.kubo.sh
        host_public_key: ((tsa-host-key.public_key))
        registration_mode: forward
      garden:
        forward_address: 127.0.0.1:7777
      baggageclaim:
        forward_address: 127.0.0.1:7788
  - name: baggageclaim
    release: concourse
    provides: {baggageclaim: {as: worker-baggageclaim}}
    properties:
      log_level: debug
      bind_ip: 127.0.0.1
  - name: garden
    release: garden-runc
    properties:
      garden:
        forward_address: 127.0.0.1:7777
        listen_network: tcp
        listen_address: 127.0.0.1:7777

update:
  canaries: 1
  max_in_flight: 1
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
