---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    tag: stable

inputs:
  - name: release-dir
  - name: git-kubo-etcd

run:
  path: git-kubo-ci/scripts/etcd/create-release.sh

outputs:
  - name: release
