---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    tag: stable

inputs:
  - name: git-kubo-ci
  - name: git-kubo-etcd

run:
  path: git-kubo-ci/scripts/etcd/create-etcd-release.sh

outputs:
  - name: etcd-release
