---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfinfrastructure/deployment

inputs:
  - name: git-kubo-ci
  - name: ci
  - name: etcd-release
  - name: consul-release
  - name: stemcell
  - name: turbulence-release
  - name: latest-etcd-release
  - name: gcs-bosh-creds
  - name: kubo-lock

run:
  path: git-kubo-ci/scripts/etcd/run-eats.sh

params:
  TEST_enable_turbulence_tests:
  TEST_parallel_nodes:
