platform: linux
image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    tag: stable
run:
  path: git-kubo-ci/scripts/etcd/setup-eats-infrastructure.sh

inputs:
- name: git-kubo-ci
- name: git-kubo-deployment
- name: kubo-lock
outputs:
- name: bosh-state
- name: bosh-creds
