---
- type: replace
  path: /instance_groups/name=master/jobs/name=kube-controller-manager/properties/k8s-args?/horizontal-pod-autoscaler-cpu-initialization-period?
  value: 1m0s

- type: replace
  path: /instance_groups/name=master/jobs/name=kube-controller-manager/properties/k8s-args?/horizontal-pod-autoscaler-downscale-stabilization?
  value: 1m0s

- type: replace
  path: /instance_groups/name=master/jobs/name=kube-controller-manager/properties/k8s-args?/horizontal-pod-autoscaler-sync-period?
  value: 10s
