- type: replace
  path: /instance_groups/name=worker/azs
  value: [ z1, z2, z3 ]

- type: replace
  path: /instance_groups/name=worker/instances
  value: 3

- type: replace
  path: /variables/name=tls-kubernetes/options/alternative_names/-
  value: ((master_ip))
