- type: replace
  path: /instance_groups/name=worker/azs
  value: [ z1, z2, z3 ]

- type: replace
  path: /instance_groups/name=worker/instances
  value: 3

- type: replace
  path: /variables/name=tls-kubernetes/options/alternative_names/-
  value: ((master_ip))

  # To override the existing deployment check in deploy_utils.genrate_manifest()
- type: replace
  path: /update/max_in_flight
  value: 100%
