- type: replace
  path: /instance_groups/name=master/jobs/name=kube-apiserver/properties/port
  value: ((kubernetes_master_port))

- type: replace
  path: /variables/name=tls-kubernetes/options/common_name
  value: ((kubernetes_master_host))

- type: replace
  path: /variables/name=tls-kubernetes/options/alternative_names/-
  value: ((kubernetes_master_host))

