- type: remove
  path: /instance_groups/name=master/networks/name=default

- type: replace
  path: /instance_groups/name=master/networks/-
  value:
    name: ((network_name))

- type: remove
  path: /instance_groups/name=worker/networks/name=default

- type: replace
  path: /instance_groups/name=worker/networks/-
  value:
    name: ((network_name))

- type: remove
  path: /instance_groups/name=apply-addons/networks/name=default

- type: replace
  path: /instance_groups/name=apply-addons/networks/-
  value:
    name: ((network_name))
