- type: replace
  path: /instance_groups/name=worker/azs
  value: [ z1, z2, z3 ]
- type: replace
  path: /instance_groups/name=master/instances
  value: 3
- type: replace
  path: /instance_groups/name=master/azs
  value: [ z1, z2, z3 ]
