- type: replace
  path: /azs/name=z2?
  value:
    name: z2
    cloud_properties:
      zone: us-east1-b

- type: replace
  path: /azs/name=z3?
  value:
    name: z3
    cloud_properties:
      zone: us-east1-d

- type: replace
  path: /networks/name=default/subnets/0/azs?
  value: [ z1, z2, z3 ]

- type: remove
  path: /networks/name=default/subnets/0/az?

- type: replace
  path: /networks/name=default/subnets/0/cloud_properties/ephemeral_external_ip?
  value: true
